### ISSUE TITLE
LegendaryReplays

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#104]
Fix it so that everything aligns with each other.

**Comment by juaoose** [comment]
Hello there Eddy,

Divi (a guy from loldevs that worked with spectator data) just released some new project which is based on a replay system, maybe it could provide some info to LCs replay handling.

The project is here: https://github.com/EloGank

**Comment by eddy5641** [comment]
I am looking at this https://github.com/mhuggins/BaronReplaysSrc (Baron Replays ~ c# replay system). I will take a look at that as well.Thanks :)

**Comment by NitroXenon** [comment]
Hay eddy here is the new source code of BaronReplays I just decomplied. I have used de4dot to deobfuscate it but it didn't work.

Btw, hope this can help you developing the replay logic :)

Repo: 
https://github.com/NitroXenon/BaronreplaySrc-New

**Comment by eddy5641** [comment]
now a milestone
