### ISSUE TITLE
Loading image

### ISSUE THREAD

**Issue by horato** [SightstoneOfficial/LegendaryClient#124]
I propose this to be our new loading image/gif/video whatever.
http://img-9gag-ftw.9cache.com/photo/aGVAE3X_460sv.mp4

**Comment by Dispersia** [comment]
I've seen that in several places. I'm probably copywrited somewhere, so search around and make sure before we even consider it :P

**Comment by Dispersia** [comment]
Just checked, copywrited so unless you want to ask permission on Deviant, can't use
