### ISSUE TITLE
Auto replay recording

### ISSUE THREAD

**Issue by horato** [SightstoneOfficial/LegendaryClient#125]
Hey,
I've noticed that now, when game is starting, we have 2 game recorders running, There is one in Client.cs in LaunchGame method that needs ReplayRecorder.exe and then there is 2nd recorder which I added few days back with settings option to turn off auto recording and executing itself from within code (no exe required). There is one in ChampSelectPage.xaml.cs and I've just added one in teambuilder as I am working on it atm. 
My question is: which one do we keep?

**Comment by eddy5641** [comment]
The one that is in the LaunchGame method seems to not work (Not sure why, it doesn't get the chunks). I added the ReplayRecorder to solve this. So I guess remove the on in LC then keep ReplayRecorder. Possibly hide it as well as soon as the users will not need to see it (then use pipes to communicate to LegendaryClient)

**Comment by horato** [comment]
I might be little tired or something.. i have no idea what are you talking about :D What do I remove then?

**Comment by eddy5641** [comment]
Remove the one in lc and keep the replayrecorder

**Comment by horato** [comment]
You said it does not work no? Why should we keep something thats not working? :d

**Comment by eddy5641** [comment]
The one in LC sometimes bugs out and doesn't record the game (Might have to do with unloading of the pages)

**Comment by horato** [comment]
There were an issue I fixed few hours back in 8504d97f163264c2a9cea43b4e4028d58523e659. Could that be the problem?
