### ISSUE TITLE
Solo Queue

### ISSUE THREAD

**Issue by drkcodeman** [SightstoneOfficial/LegendaryClient#143]
Unable to Solo Queue for anything.

**Comment by Dispersia** [comment]
They are simply disabled, not an issue, just use team queue page, it's the same thing as solo queueing just don't invite friends :P

**Comment by drkcodeman** [comment]
Thanks :)  btw great work guys!

**Comment by drkcodeman** [comment]
Tried team queue for bot games just sits there

**Comment by Dispersia** [comment]
OH YA, bot games don't work, thank you for reminding me to disable it >.<, only normal, draft, aram, and ranked work completely, the rest are either incomplete (teambuilder) but work, or they simply haven't been finished, sorry

**Comment by drkcodeman** [comment]
lol ok
