### ISSUE TITLE
2.2.0.0 nickname problem

### ISSUE THREAD

**Issue by vperpl** [SightstoneOfficial/LegendaryClient#149]
Earlier version were working fine for me but with the recent i have a problem whenever i try to play - "TEAM QUEUE" it crashes, i think it have problem with my Nick containing symbol " Í "
when i login it failz to do something & the chat doesnt work 

logged on anyother account - works fine.

**Comment by Dispersia** [comment]
do you know if the version right before 2.2.0.0 worked fine or is that just when you noticed it? would just make finding the issue easier

**Comment by vperpl** [comment]
2.1.0.3 was working fine. it happend in recent version both of them 2.2.0.0 & 2.2.0.1 dont like mine nickname lel

**Comment by Dispersia** [comment]
I actually can't find a change that would make it not work... this sounds like a jabber-net issue but none of that changed. What server do you have the username with a weird character on? Is it one that is allowed or?

**Comment by vperpl** [comment]
EUNE i can give you my login & password throu skype so u can debug it urself 
addme: vperpl

**Comment by nairaner** [comment]
I've account with nick 나이란, it works even though you can't make a name like this anymore. Can you upload log?

**Comment by vperpl** [comment]
here
https://mega.co.nz/#!joUhBQqY!JKVojZbcd85xblZpJ8JHed48UF2DUmLYEaX-Xsztza4

**Comment by vperpl** [comment]
btw i tested it on different account & works fine, only on this one i have problem lel.

**Comment by Dispersia** [comment]
This was fixed
