### ISSUE TITLE
Featured Games - Needs to Refresh every x Minutes

### ISSUE THREAD

**Issue by Dispersia** [SightstoneOfficial/LegendaryClient#162]
Also needs to refresh every x minutes.

**Comment by Zer0code** [comment]
[<i>low priority issue</i>] ;)

**Comment by horato** [comment]
timer hopefuly fixed (if not imma cry) e9c6a670c73b8785fca69a0ee25ecfb955232a96
TODO: refresh every x minutes

**Comment by secretdataz** [comment]
Added in ff505e6
