### ISSUE TITLE
Hey

### ISSUE THREAD

**Issue by maxiking913** [SightstoneOfficial/LegendaryClient#170]
I checked out and i have a question.

With this client, it is possible to pick all champs or it is serversided?

(Ps: I dont get it, it shows only oned champs and f2p. Doesnt matter i do do allchamps, not ownedchamps)

And maps, its old 3 vs 3 map on cusotm games possible? (I think so; BUT I DONT REALLY KNOW :D)

and urf, custom games urf when replace normal 5 v 5 to urf 5 v 5? (under gamemode settings?

**Comment by Dispersia** [comment]
I will look into the making an old 3v3 map and will respond if you can. Picking all champs is server sided - however who you can trade with is client sided, so technically you could trade to have anyone. And no, urf has to be enabled on their servers for custom games or real game modes of it to be played so unfortunately they can't be played at the moment, sorry!

**Comment by nairaner** [comment]
they changed something in 4.16 and old 3v3 is no longer possible to play, 
source http://leaguesandbox.com/forum/thread-141.html

**Comment by maxiking913** [comment]
But isnt it possbile that we can "spoof" or show the champion icon and then we can select it. On winterminds client it was working too. so we can add (Shownotowned champs on champ select)?
I think it must be working.

**Comment by eddy5641** [comment]
I am working on porting intwars over to c# to allow all collaborators to understand the code.

**Comment by maxiking913** [comment]
That means?

**Comment by eddy5641** [comment]
it will allow you to connect to a custom server and that unlocks all the champs. I can see if it allows you to select champions you do not own, but I think that was patched
