### ISSUE TITLE
crash when entering champ select

### ISSUE THREAD

**Issue by nairaner** [SightstoneOfficial/LegendaryClient#171]
Some account crash on entering champ select 
Logs from one person on 2 accounts: 
Crash http://pastebin.com/exkQizcN
Working http://pastebin.com/sNQaVBGV

I think i saw some logs with exacly the same error somewhere, so its not only one person.

**Comment by Dispersia** [comment]
jabber-net error. Whoever these accounts were ask if they could see their friends, if not then they might not have connected to chat in which I would need to debug jabber-net to see why not

**Comment by eddy5641** [comment]
Question do you have odd chars such 好? That may be a problem, but it seems to be a problem with the Room.join, Add try and catch there

**Comment by nairaner** [comment]
I talked to him on irc and i was told he could see his friends and doesnt have any unusual characters in nick.
