### ISSUE TITLE
Empty Gamescouter

### ISSUE THREAD

**Issue by MarcusD-Tritus** [SightstoneOfficial/LegendaryClient#172]
Hi, I played an ARAM game to test new version, and I found a bug : after launching the game, the Gamescouter started, but it was empty, no player was displayed in it. Here is the log of the session, from starting the launcher to closing it, with one ARAM game between : http://pastebin.com/LAUCKmVv
Since my Windows is in French, just ask me if you need me to translate you something. Hope it'll help you =).

**Comment by eddy5641** [comment]
odd
try playing another game and go to profile and launch the gamescouter from there. Also the gamescouter is buggy. I still need more work
