### ISSUE TITLE
Reasearch

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#175]
http://cdn.leagueoflegends.com/patcher/data/regions/(#REGION#)/champData/freeToPlayChamps.json
http://status.leagueoflegends.com/shards/(#REGION#)/summary
http://ll.leagueoflegends.com/pages/launcher/(#REGION#) ["-" + Optional Locale]

**Comment by eddy5641** [comment]
http://cdn.leagueoflegends.com/patcher/data/locales/en_US/champData/champData(ChampID).json
#Example
http://cdn.leagueoflegends.com/patcher/data/locales/en_US/champData/champData266.json

**Comment by horato** [comment]
2f10d9d0c46b8f3bedab5364b4336d895b4a4ea3 538389e7350408503e7e32b003e83b045dc87204 I'll make more as soon as I figure out what they are good for.

**Comment by eddy5641** [comment]
I think that these would be ulta useful for the patcher because we can not get the freeweek anymore over rtmp
