### ISSUE TITLE
After champion selection, window spam

### ISSUE THREAD

**Issue by gozzy1** [SightstoneOfficial/LegendaryClient#178]
After champion selection on the poro gamemode, 5 different instances of league opened and also 5 gamescouters

**Comment by nairaner** [comment]
not fixed. Happens when you have trade request open? maybe?

**Comment by Dispersia** [comment]
I believe this was fixed, correct? Just trying to get these old issues removed.

**Comment by gozzy1** [comment]
Not sure man. if it comes back should I make a new one?

**Comment by Dispersia** [comment]
Please do! I'm 99% this was fixed, but if not feel free to reopen ^^

**Comment by nairaner** [comment]
I think it happened to me yesterday. It happens when someone dodges in champselect. After that queue pops several times same with champ select and in game page and check doesnt work because all happens simultaneously before process is started.
