### ISSUE TITLE
Login Image

### ISSUE THREAD

**Issue by horato** [SightstoneOfficial/LegendaryClient#179]
Yo,
so - do we want to keep the championship login thing forever or do we change? I propose two solutions:
1. from l3cdn; in packagemanifest there are several login screens (at least now) in /files/mod/lgn/themes/login\* - we could either: 
   - download them all with each patch and randomly cycle
   - download one randomly selected each time client opens 
   - note: there is probably no way to figure out which one is curently being used as they are all from same release
2. masta copy pasta from league folder actual login animation, again with two options either on patch or on each login

(same applies to all login page related stuff - animation, non-animated img, sounds,...)
also, I just opened fresh install and there is only black screen instead of login animation kek.

**Comment by nairaner** [comment]
Next used theme is first in theme.properties, its edited when closing client. We tried to not use swf themes thats why eddy made mp4 version.
Nvm, I used LSI to randomly change login screen and didnt notice...

**Comment by eddy5641** [comment]
delete the .mp4 and .mp3 login files (In your lc dir)

**Comment by eddy5641** [comment]
3rd option, find out how lol selects the correct login screen and use that

**Comment by nairaner** [comment]
Its the first one in theme.properties

**Comment by horato** [comment]
I think we should be less dependant on riot client so we could use the l3cdn
BUT the theme.properties is not included in every release. Latest: http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/0.0.1.128/files/theme.properties
and for some reason releaselisting http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/releaselisting_EUNE does not show the 1.128 release lol

**Comment by nairaner** [comment]
riot fucked up release again. 1.129 is just empty, no new files http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/0.0.1.129/packages/files/packagemanifest

**Comment by horato** [comment]
It doesn't look empty to me :D

**Comment by nairaner** [comment]
there is no files with version number 0.0.1.129

**Comment by horato** [comment]
9e0de65e35ff1c1ce8816a6a1037c1136b018dd2 
now what? There is bunch of files that does not make much sense.

**Comment by secretdataz** [comment]
Login screen works fine now. Can be closed.
