### ISSUE TITLE
Failing to load full friend list

### ISSUE THREAD

**Issue by bziur** [SightstoneOfficial/LegendaryClient#186]
Apparently my instance of the client fails to load full friend list. It loads 4 groups, 5th it skips, and then it fails to connect to queue (jabber null return). I'm playing on EUNE.
On EUW I haven't encountered the problem.

(1/9/2015 12:30 PM) [LOG]: LegendaryClient Started Up Successfully
(1/9/2015 12:30 PM) [LOG]: Starting Patcher
(1/9/2015 12:30 PM) [LOG]: DataDragon Version: 4.21.5
(1/9/2015 12:30 PM) [LOG]: Current DataDragon Version: 4.21.5
(1/9/2015 12:30 PM) [LOG]: DDragon Version (LOL Version) = 4.21.5
(1/9/2015 12:30 PM) [LOG]: Client Version: 4.21.5
(1/9/2015 12:30 PM) [LOG]: Air Assets Version: 0.0.1.124
(1/9/2015 12:30 PM) [LOG]: Current Air Assets Version: 0.0.1.124
(1/9/2015 12:30 PM) [LOG]: Trying to detect League of Legends GameClient
(1/9/2015 12:30 PM) [LOG]: League of Legends is located at: D:\Games\League of Legends\
(1/9/2015 12:30 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.71
(1/9/2015 12:30 PM) [LOG]: Checking if League of Legends is Up-To-Date
(1/9/2015 12:30 PM) [LOG]: League of Legends is Up-To-Date
(1/9/2015 12:30 PM) [LOG]: LegendaryClient Has Finished Patching
(1/9/2015 12:30 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:30 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(1/9/2015 12:30 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: An invalid IP address was specified.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(1/9/2015 12:31 PM) [LOG]: Connected to EUNE and logged in as Fellow Foe
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: Application identity is not set.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: No imaging component suitable to complete this operation was found.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: No imaging component suitable to complete this operation was found.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: No imaging component suitable to complete this operation was found.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: No imaging component suitable to complete this operation was found.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Windows.Media.Imaging.BitmapDecoder.SetupDecoderFromUriOrStream(Uri uri, Stream stream, BitmapCacheOption cacheOption, Guid& clsId, Boolean& isOriginalWritable, Stream& uriStream, UnmanagedMemoryStream& unmanagedMemoryStream, SafeFileHandle& safeFilehandle)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(1/9/2015 12:31 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: Unexpected end of file has occurred. The following elements are not closed: note, item. Line 1, position 112.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: Unexpected exception
(1/9/2015 12:31 PM) [EXCEPTION]:    at jabber.protocol.AsynchElementStream.Push(Byte[] buf, Int32 offset, Int32 length)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(1/9/2015 12:31 PM) [EXCEPTION]:    at jabber.connection.XmppStream.Write(XmlElement elem)
(1/9/2015 12:31 PM) [EXCEPTION]: A first chance exception was thrown
(1/9/2015 12:31 PM) [EXCEPTION]: The read operation failed, see inner exception.
(1/9/2015 12:31 PM) [EXCEPTION]:    at System.Net.Security._SslStream.ProcessRead(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)

**Comment by nairaner** [comment]
does it still happed?

**Comment by bziur** [comment]
Haven't encountered it in a while.
