### ISSUE TITLE
Crashing as soon as i join queue.

### ISSUE THREAD

**Issue by ar1a** [SightstoneOfficial/LegendaryClient#187]
No debug, just crashes, cant think of cause atm...

Server: OC1
OS: Windows 7
Not a hardware issue

**Comment by nairaner** [comment]
log?

**Comment by ar1a** [comment]
No log.

**Comment by nairaner** [comment]
just upload log from log folder or join the IRC

**Comment by ar1a** [comment]
What irc? Also i have permissions to push updates.

**Comment by nairaner** [comment]
http://kiwiirc.com/client/irc.freenode.net/#LegendaryClient

**Comment by Noobgam** [comment]
Nairaner. For some reason same thing happens with me and I am also unable to join IRC for some reason. 
http://pastebin.com/xs3vV7Y4 - Log
For some reason it crashes when tries to get champs for ban.
