### ISSUE TITLE
Ranked Team invite causes a crash

### ISSUE THREAD

**Issue by ShadowsTear** [SightstoneOfficial/LegendaryClient#190]
When invited to a ranked team, the client will crash.

**Comment by nairaner** [comment]
Will no longer crash, but cant accept, using function from PVPNetConnect doesn't work

**Comment by eddy5641** [comment]
I have to go on a big packet hunt, this includes draft (Ranked)

**Comment by horato** [comment]
fixed 140f1357241542b3441973d4f7473b63874d33fa + b1aa4131dc804ff8f3d2d2384bc29ea9797c0709
