### ISSUE TITLE
More crashes on champ select.

### ISSUE THREAD

**Issue by ar1a** [SightstoneOfficial/LegendaryClient#192]
Precalled stuff, joining a normal
http://pastebin.com/kP0gNph0

**Comment by ar1a** [comment]
These are getting really annoying, 3rd time this has happened 
- You have 12m:48s remaining until you may queue again

**Comment by horato** [comment]
this part of log is not the one that causes crash.

**Comment by ar1a** [comment]
Its the whole log. (Cutting out the start)

**Comment by horato** [comment]
Then it must be somewhere in what you cut out. The thing that crashes the cient (legendaryclient.exe has stopped working) is labeled as [UNHANDLEDEXCEPTION]. What you posted is just information from jabber.net, the part that handles chat and friendlist.

**Comment by eddy5641** [comment]
There should be more info earlier on, these are just PVPNet spasms (Or xmpp but I think it is PVPNet) that need to be removed from logs.

**Comment by nairaner** [comment]
ca87c660a860eb0e179a17198c20f6be087a93a1
