### ISSUE TITLE
Garena PH not working. My League of Legends says it is updated but LC says not. :/

### ISSUE THREAD

**Issue by iStation** [SightstoneOfficial/LegendaryClient#195]
![123](https://cloud.githubusercontent.com/assets/10657880/5861486/b68220c4-a2a4-11e4-9bf6-4f6a7815681c.jpg)

Does LC support garena? :(

BTW here is the lol.properties file:

host=prodph.lol.garenanow.com
xmpp_server_url=chatph.lol.garenanow.com
xmpp_accept_self_signed_cert=true
startChat=true
storeEnabled=true
enableTutorialGame=true
lobbyLandingURL=http://lol.garena.ph/lolphlauncher/
ladderURL=http://lol.garena.ph/ladder-rankings
lq_uri=https://lqph.lol.garenanow.com
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0

**Comment by nairaner** [comment]
ohh there is no version check for garena... need to figure out where is the latestversion
probably somewhere here http://cdn.garenanow.com/gamelauncher/update/lol-new

**Comment by nongnoobjung** [comment]
@nairaner  http://updateres.garenanow.com/im/versions.xml compare with lol.version in  C:\GarenaLoL\GameData\Apps\LoLTH

**Comment by iStation** [comment]
@nairaner Is it fix?

**Comment by horato** [comment]
There is b1b58cec38cd745b0e702e007b0827a2308a506a so I assume it will be fixed on next release
