### ISSUE TITLE
Cant change summoner spells on low lvl accounts

### ISSUE THREAD

**Issue by bziur** [SightstoneOfficial/LegendaryClient#196]
On accounts without all summoner spells I can't pick summoner spells. It allows me to select them in the dialog, just doesn't update them once selected in the client.

**Comment by bziur** [comment]
UPDATE: Apparently it only occurs when trying to select smite.

**Comment by eddy5641** [comment]
maybe level data. I will check if it is correct

**Comment by nairaner** [comment]
they changed min level for smite 6->12 and flash 12 ->6 or something like that

**Comment by eddy5641** [comment]
ahh that is why than
