### ISSUE TITLE
Random champion on low lvl accounts

### ISSUE THREAD

**Issue by bziur** [SightstoneOfficial/LegendaryClient#197]
I noticed a bug that I couldn't select a champion on my low lvl account possible case would be lack of owned champions. So after locking in I was getting totally random champion (even non-free this week one).

**Comment by nairaner** [comment]
do you mean 1-10lvl account?

**Comment by bziur** [comment]
My account was lvl 3-6. And I didn't have a champion bought. Since I bought Annie I haven't encountered the problem. Which Is kinda shame because I enjoyed this bug xD

**Comment by nairaner** [comment]
we might show weekly rotation but account 1-10 have, no rotation only 10 selected easy champs

**Comment by eddy5641** [comment]
what champions did it allow you to select?

**Comment by bziur** [comment]
Available: gnar, ashe, fiddle, azir, lissandra, morgana, shaco, singed, sona, twitch... (wouldn't select them after clicking them, even though the background updated like they were, they wouldn't show up on my character in champ selection)
I rolled: wukong, riven, jinx, can't remember if more for sure
Now theyre the same, but I have annie and sion, and I can select every one.

**Comment by nairaner** [comment]
Should be fixed now
