### ISSUE TITLE
Cannot join any queues (PLAYERQUIT)

### ISSUE THREAD

**Issue by niktamerfdp** [SightstoneOfficial/LegendaryClient#204]
I cannot join queues, i always get a window with "PLAYERQUIT" as title and a random number that depends the account I'm playing on (it's user id i guess).

When I click ok, the window closes and it leaves me "in queue".

**Comment by eddy5641** [comment]
Are you using solo queue or teamqueue page

**Comment by niktamerfdp** [comment]
I'm clicking on the single "Queue (beta)" button. When I click on Teamqueue, nothing happens.

**Comment by nairaner** [comment]
can you upload log?

**Comment by niktamerfdp** [comment]
http://pastebin.com/hFCjiXJn

edit: I logged in, clicked on "Queue (beta)" and i had the playerquit window. With auto accept queue checked on or off, it does the same.

**Comment by nairaner** [comment]
which queue did you try to join? At level 3 i think you can only join intro bots which dont work. 

TODO: Add message for queue with lower level accounts about required level

**Comment by niktamerfdp** [comment]
I am level 5 and I tried to join Beginner botgames.
(acc got banned in banwave)

**Comment by nairaner** [comment]
bot game dont work yet, will push update soon for team queue

**Comment by niktamerfdp** [comment]
Oh okay, thanks!
