### ISSUE TITLE
Crash in Champ select

### ISSUE THREAD

**Issue by MarcusD-Tritus** [SightstoneOfficial/LegendaryClient#206]
Hi, I played some ARAMS, and found a recurring bug : each time someone leave in champion select, when I enter again in champ select for the next game, the game crash. Did it 3 times a row. Seems to happen only when someone leaved, and even if I leave the queue and then re-enter. Here are the logs : http://pastebin.com/MwNDvVct. Hope it'll help you ! =)

**Comment by eddy5641** [comment]
Line 339 + Line 279
That is the error
Okay will check it out
