### ISSUE TITLE
Titlebar queue timer alternating between previous queue time 

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#208]
Just a minor bug, I'll try to explain it. After returning from a game and re-queuing from the Team Queue (assuming LegendaryClient hadn't been closed), the queue timer alternates each second between the previous queue time and the real queue time as if it was "stacked" on top of each other.

So if were to queue up for a game and the game ends, the timer would still keep counting the time from the previous game I queued for.

So for example if I were to queue up without having closed LegendaryClient , it would alternate between queue timers as if I was still in queue for the previous game I had played.

The queue timer would look something like this each second when this bug happens:
00:01 / 32:10 / 00:03 / 32:12 / 00:05 / 32:14 / 00:07 /... and so on.

32:10 represents the previous queue time.
00:01 represents the time of the queue you just recently joined.

The bug is temporary fixed by relaunching LegendaryClient.

**Comment by eddy5641** [comment]
This is because the queue timer is messed and doesn't initialize again, the old timer when it ticks changes the textbox and the new timer changes it. It gets worse when you go into a lot of queues. Easy fix would be move timer to client.cs
