### ISSUE TITLE
Post-game screen, 6 out of 7 inventory slots

### ISSUE THREAD

**Issue by bziur** [SightstoneOfficial/LegendaryClient#213]
An item is left out.
Pretty sure this doesn't need a screen but here it is:
[legendaryclient](http://prntscr.com/644djn) & [online match history](http://prntscr.com/644dqz)

**Comment by nairaner** [comment]
work for me http://puu.sh/fODl7/9e6b2349e6.jpg...

**Comment by nairaner** [comment]
which windows do you have?

**Comment by bziur** [comment]
Windows 7 x86. Desktop resolution 1366x768. Also I have desktop compositioning (aero?) disabled if it matters at all.

**Comment by nairaner** [comment]
it might be putting 7th item in another row because there is no space in the first one. I dont really know much about ui and it doesnt happen to me so cant help

**Comment by bziur** [comment]
It's not a HUGE deal really. Just puting it out there. Someday can be fixed ;)

**Comment by nairaner** [comment]
explained in #244
