### ISSUE TITLE
Pre-game screen

### ISSUE THREAD

**Issue by bziur** [SightstoneOfficial/LegendaryClient#214]
Small graphical Glitch on the bottom.
Window not fitting on smaller screens.
It seems that pre-game screen loads information about players to some point
and then it gives up, giving 100/100/100 to everyone. Also tooltop is empty.

http://prntscr.com/6454ff

**Comment by eddy5641** [comment]
why is it saying 100/100/100, it should say no recent games...
Opps I will fix that
The tooltop is going to take longer because I will have to manually retrieve data

**Comment by eddy5641** [comment]
I just tried this but I can not reproduce it, can you send logs?

**Comment by bziur** [comment]
http://d.pr/f/11mJu here's the latest one that has gamescouter error in it.
Tell me if you need more.
