### ISSUE TITLE
if select local rune page in champ select, it crashed. and would be nice if we can edit local rune pages like normal rune pages

### ISSUE THREAD

**Issue by maxiking913** [SightstoneOfficial/LegendaryClient#215]
(12.02.2015 16:48) [LOG]: LegendaryClient Started Up Successfully
(12.02.2015 16:48) [LOG]: Starting Patcher
(12.02.2015 16:48) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:48) [LOG]: DataDragon Version: 5.3.1
(12.02.2015 16:48) [EXCEPTION]: Die Datei oder Assembly "mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" oder eine Abhängigkeit davon wurde nicht gefunden. Das System kann die angegebene Datei nicht finden.
(12.02.2015 16:48) [LOG]: Current DataDragon Version: 5.3.1
(12.02.2015 16:48) [LOG]: DDragon Version (LOL Version) = 5.3.1
(12.02.2015 16:48) [LOG]: Client Version: 5.3.1
(12.02.2015 16:48) [EXCEPTION]:    bei System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   bei System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(12.02.2015 16:48) [LOG]: Air Assets Version: 0.0.1.129
(12.02.2015 16:48) [LOG]: Current Air Assets Version: 0.0.1.129
(12.02.2015 16:48) [LOG]: Trying to detect League of Legends GameClient
(12.02.2015 16:48) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(12.02.2015 16:48) [LOG]: Latest League of Legends GameClient: 0.0.1.76
(12.02.2015 16:48) [LOG]: Checking if League of Legends is Up-To-Date
(12.02.2015 16:48) [LOG]: League of Legends is Up-To-Date
(12.02.2015 16:48) [LOG]: LegendaryClient Has Finished Patching
(12.02.2015 16:48) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:48) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:48) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:48) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:48) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:48) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:48) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:48) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:48) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:48) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:48) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:48) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Es wurde eine ungültige IP-Adresse angegeben.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(12.02.2015 16:49) [LOG]: Connected to EUW and logged in as Valnar is Beast
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Die Datei "C:\Riot Games\League of Legends\RunePages\Valnar is Beast" konnte nicht gefunden werden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Eine Ausnahme vom Typ "xpnet.PartialTokenException" wurde ausgelöst.
(12.02.2015 16:49) [EXCEPTION]:    bei xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Die Anwendungsidentität ist nicht festgelegt.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.HttpWebRequest.GetResponse()
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Der Remoteserver hat einen Fehler zurückgegeben: (404) Nicht gefunden.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(12.02.2015 16:49) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:49) [EXCEPTION]: Die arithmetische Operation hat einen Überlauf verursacht.
(12.02.2015 16:49) [EXCEPTION]:    bei System.Double.System.IConvertible.ToInt64(IFormatProvider provider)
(12.02.2015 16:49) [LOG]: COUNTER_PICK
(12.02.2015 16:50) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:50) [EXCEPTION]: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Auflistung sein.
Parametername: index
(12.02.2015 16:50) [EXCEPTION]:    bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
(12.02.2015 16:50) [EXCEPTION]: A first chance exception was thrown
(12.02.2015 16:50) [EXCEPTION]: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Auflistung sein.
Parametername: index
(12.02.2015 16:50) [EXCEPTION]:    bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei LegendaryClient.Windows.ChampSelectPage.<LocalRuneComboBox_SelectionChanged>d__a3.MoveNext() in c:\Users\luigu\Desktop\LegendaryClient-master\LegendaryClient\Windows\ChampSelectPage.xaml.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
(12.02.2015 16:50) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(12.02.2015 16:50) [UNHANDLEDEXCEPTION]: Der Index lag außerhalb des Bereichs. Er darf nicht negativ und kleiner als die Auflistung sein.
Parametername: index
(12.02.2015 16:50) [UNHANDLEDEXCEPTION]:    bei System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   bei LegendaryClient.Windows.ChampSelectPage.<LocalRuneComboBox_SelectionChanged>d__a3.MoveNext() in c:\Users\luigu\Desktop\LegendaryClient-master\LegendaryClient\Windows\ChampSelectPage.xaml.cs:Zeile 0.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__3(Object state)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   bei System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   bei System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   bei System.Windows.Threading.Dispatcher.Run()
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei System.Windows.Application.Run(Window window)
   bei LegendaryClient.App.Main() in c:\Users\luigu\Desktop\LegendaryClient-master\LegendaryClient\obj\Debug\App.g.cs:Zeile 0.

**Comment by eddy5641** [comment]
Ok will see what I can do
