### ISSUE TITLE
What is the Dev Key?

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#220]
I would like to add something in LegendaryClient ad gonna test it.

But what is that Dev Key? I can't find it...

**Comment by horato** [comment]
devkey is a file that eddy created to prevent leechers and non-coders from using dev-only features. You can ask eddy to give it to you (which he won't anyway) or find out how it works and edit it.

**Comment by NitroXenon** [comment]
Ok thx.
