### ISSUE TITLE
Garena TW login and nothing happened

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#222]
Due to the crash of LegenayClient using Garena, I manually start LC using the following args:
LegendaryClient.exe "EnableGarena=true" "TW" "tokenxxxxx"

After I started the .bat, LC did not crash and started to login. However, after a few seconds, LC went back to the login page and ask me the username and password. I cant login to Garena TW server...

Log :

(2/25/2015 11:25 AM) [LOG]: LegendaryClient Started Up Successfully
(2/25/2015 11:25 AM) [LOG]: Starting Patcher
(2/25/2015 11:25 AM) [EXCEPTION]: A first chance exception was thrown
(2/25/2015 11:25 AM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(2/25/2015 11:25 AM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(2/25/2015 11:25 AM) [LOG]: DataDragon Version: 5.3.1
(2/25/2015 11:25 AM) [LOG]: Current DataDragon Version: 5.3.1
(2/25/2015 11:25 AM) [LOG]: DDragon Version (LOL Version) = 5.3.1
(2/25/2015 11:25 AM) [LOG]: Client Version: 5.3.1
(2/25/2015 11:25 AM) [LOG]: Air Assets Version: 0.0.1.129
(2/25/2015 11:25 AM) [LOG]: Current Air Assets Version: 0.0.1.129
(2/25/2015 11:25 AM) [LOG]: Trying to detect League of Legends GameClient
(2/25/2015 11:25 AM) [LOG]: League of Legends is located at: C:\GarenaLoLTW\GameData\Apps\LoLTW\lol.exe
(2/25/2015 11:25 AM) [LOG]: Latest League of Legends GameClient: 0.0.1.78
(2/25/2015 11:25 AM) [LOG]: Checking if League of Legends is Up-To-Date
(2/25/2015 11:25 AM) [LOG]: League of Legends is Up-To-Date
(2/25/2015 11:25 AM) [LOG]: LegendaryClient Has Finished Patching
(2/25/2015 11:25 AM) [EXCEPTION]: A first chance exception was thrown
(2/25/2015 11:25 AM) [EXCEPTION]: The given key was not present in the dictionary.
(2/25/2015 11:25 AM) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

**Comment by nongnoobjung** [comment]
because it not done yet :D

**Comment by NitroXenon** [comment]
@nongnoobjung but you released a self-compiled LC that can login to Garena region... Is it?

**Comment by nongnoobjung** [comment]
i send how to get gastoken for login chat to @eddy5641  i think official LC will support on garena soon

**Comment by NitroXenon** [comment]
@nongnoobjung Chat works fine~ :)

**Comment by eddy5641** [comment]
Try now

**Comment by eddy5641** [comment]
Also do not enter a game, not sure if it loads the location of the lolgameclient

**Comment by NitroXenon** [comment]
#227

**Comment by NitroXenon** [comment]
Garena now works fine. Closed
