### ISSUE TITLE
Can't queue

### ISSUE THREAD

**Issue by atjeff** [SightstoneOfficial/LegendaryClient#225]
Do you have the build where queuing for games worked like in your video? The project files keep getting updated.

**Comment by atjeff** [comment]
queuing for a game seems to crash when join chat room initiates

**Comment by eddy5641** [comment]
can you send a log?

**Comment by NitroXenon** [comment]
My LC also crashes when I click the join queue button of 5v5 Bot (NA).

**Comment by eddy5641** [comment]
I haven't worked on bots, I will reproduce

**Comment by atjeff** [comment]
It's in champselectpage.cs in join chat when I enter the lobby

also... queues are taking like 15 minutes for ARAM.

http://pastebin.com/rWhCuiVX

**Comment by nairaner** [comment]
Solo queue is not fixed in 2.2.2.0 but i already pushed commit so it should work

**Comment by atjeff** [comment]
which commit ?
