### ISSUE TITLE
Garena join queue always throw "System.NullReferenceException" exception.

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#227]
System.NullReferenceException
Object reference not set to an instance of an object.

Methods witch throw exception :
1. ChampSelectPage ->  `Chatroom = Client.ConfManager.GetRoom(new JID(jid));`
2. PlayPage.cs -> EnteredQueue -> `Client.SetChatHover();`

I've used Visual Studio 2013 to debug it. I think it's the problem of chat client.

**Comment by eddy5641** [comment]
This is chat
I think it is because it does not login to chat or something like that

**Comment by NitroXenon** [comment]
Not really. Loging in to chat is not the problem. I can chat with my friends.

**Comment by NitroXenon** [comment]
Also the `jid` was successfully generated.

**Comment by NitroXenon** [comment]
No more exception thrown now :)
