### ISSUE TITLE
Can't Create/Join/Spectate on Garena

### ISSUE THREAD

**Issue by pondtroid** [SightstoneOfficial/LegendaryClient#231]
Stopped working(Crash) when click any Queue in any Mode / Spectate. plz help
logs
http://pastebin.com/W4SM5aqJ

I try to queue in EUW server and it work. but crash on Garena. QQ

**Comment by NitroXenon** [comment]
I found a JSON parsing error in your log. I also get this error before I add try...catch in the GetNews() method. I only get error whenever I am going to accept a match.

#227

**Comment by pondtroid** [comment]
eh, did i need VB2013 to fix this?
i think it too hard for my knowledge. but thank you, maybe i'll try.

**Comment by NitroXenon** [comment]
No need. I've fixed the news JSON parsing error. But there is another problem : the chat client makes LC crash.

**Comment by NitroXenon** [comment]
We should wait until eddy fixes it or disable the chat function (that means you cannot chat in champion select page).

You know.. Garena always suck.

**Comment by NitroXenon** [comment]
No more exception thrown now
