### ISSUE TITLE
Online match history uses original account region 

### ISSUE THREAD

**Issue by nairaner** [SightstoneOfficial/LegendaryClient#234]
Transfer makes online history not work, probably also affects all EUNE players from before the split

From what ive seen it is only used in PlayerParticipant so is imposible to get for normal use

**Comment by eddy5641** [comment]
If they transfer (na to euw) are the old games still on na or are they also on euw or are they deleted?

**Comment by nairaner** [comment]
http://matchhistory.eune.leagueoflegends.com/en/#match-history/EUW1/28315904 this is me although im on eune and 
http://matchhistory.eune.leagueoflegends.com/en/#match-history/EUN1/28315904 doesnt work

**Comment by NitroXenon** [comment]
so why dont we use those third party websites such as lolking?

**Comment by secretdataz** [comment]
How about the Riot API?

_tears stacked as a garena player_

**Comment by eddy5641** [comment]
I will see what I can do.

**Comment by Dispersia** [comment]
@NitroXenon because in projects like this, you try to stay away from 3rd party websites as much as possible. If that website is down, being slow, moves, whatever the case it breaks your application.

**Comment by NitroXenon** [comment]
Yes I agree

**Comment by NitroXenon** [comment]
But I think 3rd party websites can be used in special case such as Garena (no official api and match history).

**Comment by nairaner** [comment]
I found the way, we can use getStoreUrl to find region 
https://store.eun1.lol.riotgames.com/?account_id=28315904&original_account_id=28315904&original_platform_id=EUW1&token=*token*
