### ISSUE TITLE
Laggy problem should be fixed

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#235]
When I tried to accept a queue, it lags.
When I tried to change my masteries in the last 10s, it lags..
Also, when in the champion select page, lag will cause a timer delay problem. That means the timer is not accurate

I think that lag may affect user's experience. I even can't switch masteries page.
So, I think we should optimize the client, not just adding new features, but should keep and improve the stability of the client.

**Comment by nairaner** [comment]
Do you use "move window to from on pop and champ select"?

**Comment by NitroXenon** [comment]
No, I don't ...
