### ISSUE TITLE
Work on website

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#239]
The website is very "exciting"

**Comment by secretdataz** [comment]
Is the site open source?

**Comment by eddy5641** [comment]
yep under gh-pages https://github.com/eddy5641/LegendaryClient/tree/gh-pages

**Comment by NitroXenon** [comment]
Lol that dev key...

**Comment by NitroXenon** [comment]
should we upload some screenshots?

**Comment by voshond** [comment]
i'm willing to do a new Website. Here is an old Example of a Joomla Template i did by myself.
![wearefamily](https://cloud.githubusercontent.com/assets/2280353/6573529/01964068-c71c-11e4-8d89-7b2c5ba3cb3e.jpg)

But of course there are some Questions to be answered before making a Site.
1. Do we need a Navigation for multiple Sites?
2. What the Websites "Job/Goal"? Just a showcase for the Client or do you want to do more with it?
3. In which style should be Website be? Similiar to the Metrostyle of the App?
4. is there any real Logo?
5. What are the Features of the Client (and why would you use it)?

I think here the Importance is the Goal/Job of the Site and the Features.
Maybe someone who has more insight can throw me some of the main Features of the Client.
What i found so far:
- See Users Ranks before accepting the Que
- Lightweight Client
- Multiple Queing
- Opensource (build your own!)
- Gamerecorder
- get your Ping before you go ingame
- See how many players are in your desired Que
- (WIP) Local Runespages
- Editing Runepages while in Champ select
- Themes and Custom Login/Background-Images
- EasyHud

Edit:

I think Images of the Client are a must have. I was thinking of a Timeline Based structure With Screenshots of the Client and zoomed in Bubble that showcasing the Feature. Maybe an instruction Text and a Screen of the full Client. 

Edit 2:

for "Build your Own" i might thinking of something like this (my own Version of the MainPage).
![capture](https://cloud.githubusercontent.com/assets/2280353/6573887/9c3ee81a-c71f-11e4-824f-1ff1a6e2dff7.PNG)

**Comment by NitroXenon** [comment]
:+1:

**Comment by NitroXenon** [comment]
@eddy5641 Developer pls add mhn23

**Comment by voshond** [comment]
Hey @NitroXenon i am Collaborator since yesterday.

First of all i want to still do the website. I'm spending the last view Days on reworking the UI of the Client in order to present some sweet UI on the Website so thats why i'm not working on my Idea atm. I will do it definitly but it requires some time for the UI Ideas i have.

**Comment by NitroXenon** [comment]
Ok you are the best UI designer <3

Btw can you edit the index.html by yourself and add yourself in the developers list?
