### ISSUE TITLE
Remove MLaunch project

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#243]
We don't need it anymore, do we?

**Comment by NitroXenon** [comment]
yes no need anymore.

**Comment by NitroXenon** [comment]
but it seems to be useful for old version LC users. i think we should better keep it or let eddy to delete it.

**Comment by secretdataz** [comment]
The old version is near unplayable for me. (I've been following this repo around the time nongnoobjung come in)
There's no reason to support those imo.

**Comment by nairaner** [comment]
I dont think it was ever used, i think Eddy started working on it but gave up

**Comment by eddy5641** [comment]
It is now unused
