### ISSUE TITLE
Some UI elements using System scheme instead of its own 'custom buttons' / some stuff looks too spaced out

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#244]
On some elements such as the Runes window via the profile page and entering a comment on the report window / selecting a reason to honor in the dropdown menus, it is hard to see the text if it happens to be using the system style UI elements. In some cases where I happen to be using a third party system theme LegendaryClient will use the classic style buttons and fields and if I use something like the AeroLite theme or the default Windows theme, the color scheme of the fields and text are easy to see.

Here's an example of comparing the Window between what it looks like with the classic style buttons, AeroLite theme buttons and what it should look like as seen in editing the Runes from champion select window.

Screenshot if LegendaryClient happens to be using the Windows classic style scheme. The text in the fields are very hard to read since the color of the text blends in with the background
![classicstyle](https://cloud.githubusercontent.com/assets/10596864/6572545/22a4ac68-c767-11e4-8d4a-ed72645fec3a.PNG)

Screenshot if LegendaryClient happens to be using the AeroLite style scheme. (Also, notice how the page numbers are a lot more spaced out whereas in the classic scheme it appears to be placed 'tighter'.)

![aerolite scheme runes](https://cloud.githubusercontent.com/assets/10596864/6572551/2da692d4-c767-11e4-873d-a75345f2636b.PNG)

I think this is what it should look like, but these type of fields are only present when editing Runes from the Champion Select screen.

![nativestyle](https://cloud.githubusercontent.com/assets/10596864/6572593/6ebdaef6-c767-11e4-95cf-b221c0aaa32a.PNG)

Also here's the Match history UI where elements seem to be too spaced out on the AeroLite scheme, and it also shows up to six items which is similar to the issue posted a while ago.

~~Windows Aero scheme - everything is just too spaced out. It only shows 6 items and the boxes that show the champion portraits don't seem to be big enough to fit them all as one of them just cut off.~~
![aerolite history](https://cloud.githubusercontent.com/assets/10596864/6572557/3c060116-c767-11e4-9996-b00faacf4b64.PNG)

But in the classic style scheme the elements appear to just fit in perfectly.

Windows Classic style scheme (the sweeper is the 7th item which does not appear in the Aero scheme at all)
![classicscheme history](https://cloud.githubusercontent.com/assets/10596864/6572563/45ae6172-c767-11e4-90c9-02900d3d2166.PNG)

`27/03/2015:` So it seems that every dropdown menu uses the 'system style' scheme now instead of its own 'native buttons' so it looks messed up with the classic style under some cases. But with the Aero Lite scheme, it looks ok. I'm assuming it's because of the UI updates from 8f7d832b790f12bb66177ccd45872a9e816fb85a.

Some stuff just incase:
Operating System: Windows 8.1 x64
Display resolution: 1280×800

**Comment by Dispersia** [comment]
Was this fixed in the theme updates? I can't even login.

**Comment by Phorofor** [comment]
The Rune page fields were fixed which is very nice. The spacing issues are still there (the match history only showing 6 of 7 items on the AeroLite scheme)
