### ISSUE TITLE
Person-to-Person Chat unable to copy

### ISSUE THREAD

**Issue by voshond** [SightstoneOfficial/LegendaryClient#247]
![capture5](https://cloud.githubusercontent.com/assets/2280353/6577796/a283a7f8-c740-11e4-8c89-4ee08720a3b7.PNG)

that will probably bother a lot of users to be unable to copy links you post to your Friends etc

**Comment by secretdataz** [comment]
Confirmed. Pretty annoying

**Comment by eddy5641** [comment]
Another thing, you can not see any messages there are too many messages (Just message yourself from an alt account several times and soon you will not be able to read them

**Comment by secretdataz** [comment]
TODO
- [x] Make chat selectable
- [x] Style it properly

I'm not good in styling controls so someone else have to do it.

**Comment by voshond** [comment]
will sit on it

**Comment by voshond** [comment]
fixed in 7d260f5559314c1d184178939e1e6846b250e54c
