### ISSUE TITLE
Rank does not get shown if you use LC

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#252]
Maybe it is because of my "Rankchanger"? Currently no time to look into it.

**Comment by voshond** [comment]
could reproduce this without devkey was signed in with my main into LC and my alt into the normal Client by Riot. couldn't see my Rank.

**Comment by nairaner** [comment]
might load rank for season 4

**Comment by secretdataz** [comment]
Issue still present on latest dev build. Tested on Garena TH.

**Comment by secretdataz** [comment]
someone please re-test this
