### ISSUE TITLE
Update Devauth (again lol)

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#262]
Mostly a reminder to myself to change the divider between region and summoner name since space is a valid character for Summoner names but not for Login names. Will probably change to user|region.

**Comment by secretdataz** [comment]
What if we don't change the format. But, add another possible format so it doesn't break old dev SHA1s.

**Comment by nairaner** [comment]
I dont see the point, as long as we generate the same SHA1 then it wont change anything

**Comment by newchild** [comment]
WELL nvm I am an idiot. SRY guys nvermind. I was just tired. Will close
