### ISSUE TITLE
Devs Register

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#265]
All developers please register on the forums and paste your user below so I can make you an admin (because I am new to IP.Board)

**Comment by eddy5641** [comment]
@nongnoobjung contact me about your acc

**Comment by horato** [comment]
IM THERE, IM HALPING! :d

**Comment by NitroXenon** [comment]
Registered , Username : NitroXenon

**Comment by nongnoobjung** [comment]
nongnoobjung

**Comment by nairaner** [comment]
Nairaner

**Comment by secretdataz** [comment]
secretdataz

**Comment by newchild** [comment]
newchild

**Comment by voshond** [comment]
mhn23

**Comment by eliteironlix** [comment]
jonek129

**Comment by NitroXenon** [comment]
@jonek129 LOL you are not seem to be a Dev :/

**Comment by xVirtu** [comment]
xVirtu

**Comment by huynkprovn** [comment]
adukhuyet
