### ISSUE TITLE
CI setup

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#267]
We could use site like travis-ci to build development build for users to test. (at their risk, of course)

**Comment by NitroXenon** [comment]
Lol I also have this idea. But I recommend using Appveyor. I think it is better than Travis CI in .NET .

**Comment by secretdataz** [comment]
Yeah, seems like Appveyor is better in .NET.

Poke @eddy5641

**Comment by eddy5641** [comment]
Build started
git clone -q --branch=master git://github.com/eddy5641/LegendaryClient.git C:\projects\legendaryclient
git checkout -qf b50301c20986437c5a6f3b967a8644e4da9bbb82
"C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe" "LegendaryClient.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.34209]
Copyright (C) Microsoft Corporation. All rights reserved.

  LCLog -> C:\projects\legendaryclient\LCLog\bin\Debug\LCLog.dll
RiotObjects\Platform\Game\BotParticipant.cs(58,23): warning CS0108: 'PVPNetConnect.RiotObjects.Platform.Game.BotParticipant.SummonerName' hides inherited member 'PVPNetConnect.RiotObjects.Platform.Game.GameParticipant.SummonerName'. Use the new keyword if hiding was intended. [C:\projects\legendaryclient\PVPNetConnect\PVPNetConnect.csproj]
RiotObjects\Platform\Game\BotParticipant.cs(64,23): warning CS0108: 'PVPNetConnect.RiotObjects.Platform.Game.BotParticipant.SummonerInternalName' hides inherited member 'PVPNetConnect.RiotObjects.Platform.Game.GameParticipant.SummonerInternalName'. Use the new keyword if hiding was intended. [C:\projects\legendaryclient\PVPNetConnect\PVPNetConnect.csproj]
  PVPNetConnect -> C:\projects\legendaryclient\LegendaryClient\bin\PubRelease\PVPNetConnect.dll
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "log4net". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\legendaryclient\LegendaryClient\LegendaryClient.csproj]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "MediaToolkit". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\legendaryclient\LegendaryClient\LegendaryClient.csproj]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "SharpCompress". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\legendaryclient\LegendaryClient\LegendaryClient.csproj]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(2234,5): warning MSB3284: Cannot get the file path for type library "d27cdb6b-ae6d-11cf-96b8-444553540000" version 1.0. Library not registered. (Exception from HRESULT: 0x8002801D (TYPE_E_LIBNOTREGISTERED)) [C:\projects\legendaryclient\LegendaryClient\LegendaryClient.csproj]
Windows\PatcherPage.xaml.cs(27,7): error CS0246: The type or namespace name 'SharpCompress' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Windows\PatcherPage.xaml.cs(28,7): error CS0246: The type or namespace name 'SharpCompress' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Windows\PatcherPage.xaml.cs(29,7): error CS0246: The type or namespace name 'MediaToolkit' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Windows\PatcherPage.xaml.cs(30,7): error CS0246: The type or namespace name 'MediaToolkit' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Windows\PatcherPage.xaml.cs(31,7): error CS0246: The type or namespace name 'MediaToolkit' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Windows\SettingsPage.xaml.cs(18,7): error CS0246: The type or namespace name 'SharpCompress' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Windows\SettingsPage.xaml.cs(19,7): error CS0246: The type or namespace name 'SharpCompress' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
MainWindow.xaml.cs(13,7): error CS0246: The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Properties\AssemblyInfo.cs(6,7): error CS0246: The type or namespace name 'log4net' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
MainWindow.xaml.cs(39,33): error CS0246: The type or namespace name 'ILog' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Properties\AssemblyInfo.cs(60,12): error CS0246: The type or namespace name 'XmlConfigurator' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
Properties\AssemblyInfo.cs(60,12): error CS0246: The type or namespace name 'XmlConfiguratorAttribute' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\legendaryclient\LegendaryClient\yhhmxqk1.tmp_proj]
  ReplayHandler -> C:\projects\legendaryclient\ReplayHandler\bin\Debug\ReplayHandler.exe
  LegendaryClient.Patcher -> C:\projects\legendaryclient\LegendaryClient\bin\Debug\LegendaryClient.Patcher.exe
  RiotPatch -> C:\projects\legendaryclient\RiotPatch\bin\Debug\RiotPatch.dll
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "MahApps.Metro". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\legendaryclient\LCDevWindow\LCDevWindow.csproj]
C:\projects\legendaryclient\LCDevWindow\MainWindow.xaml(1,18): error MC3074: The tag 'MetroWindow' does not exist in XML namespace 'http://metro.mahapps.com/winfx/xaml/controls'. Line 1 Position 18. [C:\projects\legendaryclient\LCDevWindow\LCDevWindow.csproj]
Command exited with code 1

We have to fix this first

**Comment by eddy5641** [comment]
https://ci.appveyor.com/project/EddyV/legendaryclient

**Comment by horato** [comment]
"ICSharpCode.SharpZipLib" missing duh

**Comment by secretdataz** [comment]
adding `nuget restore` to buildscript may help

**Comment by NitroXenon** [comment]
It should be the problem of nuget packages. We should use global packages (under the LegendaryClient repo, not only in LegendaryClient folder). 

Also, I think there are some packages missing because when I clone and start working on LC, VS say that some packages are missing and I need to install them manually.

**Comment by NitroXenon** [comment]
Also we should change some paths of DLLs in LegendaryClient.csproj because I found a DLL reference to Edward_2's desktop...

**Comment by NitroXenon** [comment]
Have a look on my new project using Metro.
I can build successfully using Appveyor.
I put the nuget folder under the repo root and for each project in my solution there a nuget config file.

https://github.com/NitroXenon/LoLToolsX-5.0

https://ci.appveyor.com/project/NitroXenon/loltoolsx-5-0

**Comment by NitroXenon** [comment]
nuget branch build success. merge

**Comment by NitroXenon** [comment]
@eddy5641 eddy plz add a build badge in README.md

**Comment by secretdataz** [comment]
CI still needs more tuning. Reopened.

**Comment by secretdataz** [comment]
[Now builds without problem ;)](https://ci.appveyor.com/project/EddyV/legendaryclient/build/2.3.0.29)

~~TODO : Upload release to GitHub~~

Edit: It's not needed.

**Comment by secretdataz** [comment]
CI is now working. You can download development builds from the artifacts menu. ;)

**Comment by NitroXenon** [comment]
build failing :/

**Comment by secretdataz** [comment]
It's LCDevWindow that's failing.
poke @eddy5641

**Comment by secretdataz** [comment]
Opps shouldn't open this
