### ISSUE TITLE
LCStartUpSplash occasionally stops working

### ISSUE THREAD

**Issue by bziur** [SightstoneOfficial/LegendaryClient#268]
http://pastebin.com/D59d2fpY

So basically the LegendaryClient will not start up for some period of time after closing it.
I get stopped working dialog. After some time it seems to start up normally. Idk what's the issue.

**Comment by Dispersia** [comment]
Based on what most of those types of errors are I'm assuming it's trying to find a file that no longer exists, if it's stopping at the startupsplash it's probably messing the zip file up. Would you mind uploading the log so I could confirm this?

**Comment by eddy5641** [comment]
If it is the spash it is because I screwed up

**Comment by bziur** [comment]
It doesn't generate any logs though. Not in logs folder.

**Comment by bziur** [comment]
Deleting `...LegendaryClient/Assets/VERSION_DDRAGON` makes the splash start normally. (though it will download DataDragon and update it.)

**Comment by eddy5641** [comment]
odd, I thought it was the version file

**Comment by bziur** [comment]
I mean if it doesn't start, and crashes, deleting the file will allow it to start the game once.

**Comment by eddy5641** [comment]
Remove splashupdate. We will not be using it in future version (Actual patcher in progress)
