### ISSUE TITLE
Crash while changing mastery 

### ISSUE THREAD

**Issue by TonyRL** [SightstoneOfficial/LegendaryClient#280]
it crashes while changing mastery in ban pick stage 

log file: http://pastebin.com/8LsdaLJm

**Comment by TonyRL** [comment]
PS: Garena TW

**Comment by NitroXenon** [comment]
Also have this problem : #279

**Comment by NitroXenon** [comment]
lol I can't find any unhandled exception in your log. Did you paste a wrong log file?

**Comment by secretdataz** [comment]
Seems to be caused by a fixed issue. Please try using a development build.

**Comment by NitroXenon** [comment]
@secretdataz Not really. My LC crash too.

**Comment by TonyRL** [comment]
still crash when i change my mastery
log: http://pastebin.com/VW22HdtB
using latest dev build 2.3.0.91

**Comment by NitroXenon** [comment]
@at5393 sad but true. dont know how to fix. Also can you please open a new issue?

**Comment by NitroXenon** [comment]
yes. dont know how to fix :p

**Comment by eddy5641** [comment]
Try now, use a custom game
