### ISSUE TITLE
Garena sniff thread do not stop

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#296]
You can reproduce this by logging in via garena messenger twice.
You should see two received token message in the log.

**Comment by angus1208** [comment]
hey~ 
(2015/3/18 下午 02:46) [LOG]: LegendaryClient Started Up Successfully
(2015/3/18 下午 02:46) [EXCEPTION]: A first chance exception was thrown
(2015/3/18 下午 02:46) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. 系統找不到指定的檔案。
(2015/3/18 下午 02:46) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(2015/3/18 下午 02:46) [LOG]: DataDragon Version: 5.5.2
(2015/3/18 下午 02:46) [LOG]: Current DataDragon Version: 5.5.2
(2015/3/18 下午 02:46) [LOG]: DDragon Version (LOL Version) = 5.5.2
(2015/3/18 下午 02:46) [LOG]: Air Assets Version: 0.0.1.134
(2015/3/18 下午 02:46) [LOG]: Current Air Assets Version: 0.0.1.134
(2015/3/18 下午 02:46) [LOG]: Checking Theme...
(2015/3/18 下午 02:46) [LOG]: Trying to detect League of Legends GameClient
(2015/3/18 下午 02:46) [LOG]: League of Legends is located at: C:\Program Files (x86)\GarenaLoLTW\GameData\Apps\LoLTW\
(2015/3/18 下午 02:46) [LOG]: Latest League of Legends GameClient: 0.0.1.81
(2015/3/18 下午 02:46) [LOG]: Checking if League of Legends is Up-To-Date
(2015/3/18 下午 02:46) [LOG]: League of Legends is not Up-To-Date. Please Update League Of Legends
(2015/3/18 下午 02:46) [LOG]: Saved value, please restart the client to login.

How so!!  and update stop 40%...
please healp

**Comment by secretdataz** [comment]
@angus1208 it may be extracting datadragon and not really stuck.
Also, next time please open a separate issue.

**Comment by angus1208** [comment]
​

2015-03-18 14:56 GMT+08:00 secretdataz notifications@github.com:

**Comment by angus1208** [comment]
sorry...but..

I waited a long time, like a stuck
Select foot color into the game crashes

**Comment by NitroXenon** [comment]
@angus1208 just restart LC and click Skip

**Comment by NitroXenon** [comment]
@angus1208 the newest dev build has fixed that stuck in 40% problem.

**Comment by NitroXenon** [comment]
@secretdataz I remember that you've add abort. But someone removed it...

**Comment by nairaner** [comment]
Ive added it but @Dispersia has removed it

**Comment by NitroXenon** [comment]
@nairaner oic but why he removed it? caused some problems?

**Comment by secretdataz** [comment]
From what I can see. Garena login process runs everything on GetTokenThread. Should we do something about that?

**Comment by NitroXenon** [comment]
oh yes. so abort it may cause some problems.

maybe we can separate get token and login

**Comment by Dispersia** [comment]
@NitroXenon you shouldn't abort threads, ever. That feature shouldn't be in a high level thread area like C#, I simply replaced it with the boolean that let it end gracefully if it successfully logged in, if it's not exiting that means it's hanging in there and that part needs to be fixed. Thread.Abort doesn't guarantee a thread will be aborted, it could simply harden the thread and it will slowly become more and more resource intensive if you attempted to abort in a cpu-bound operation that resists its own destruction, or even crash your current application if it's editing the designer when aborted, in general, you should never use thread.abort (but I understand why he put it if it doesn't exit, but I don't have garena so I can't test WHY the thread isn't exiting because logic wise it appears it should.)

**Comment by nairaner** [comment]
can someone check if it works now? I added break after getting token

**Comment by secretdataz** [comment]
LC does not login with your fix

**Comment by secretdataz** [comment]
Ok, so this was an error on my end.

**Comment by nairaner** [comment]
so did it work or not?

**Comment by Dispersia** [comment]
is there a way to download garena as an NA player, even if I have to download their client? I really want to cleanup and get rid of that thread but I don't want to completely break it.

**Comment by nairaner** [comment]
just on http://lol.garena.com/home but you will have to change country in garena messager option
