### ISSUE TITLE
 New Color Theme

### ISSUE THREAD

**Issue by Dispersia** [SightstoneOfficial/LegendaryClient#306]
Instead of having the gray for everything, do we want to move everything over to the color of the theme, I gave a small demo showing just accented buttons, but it could be applied to everything if wanted, just want opinions, it's easy to revert. 

 I just find the gray to be really, really ugly.

**Comment by nairaner** [comment]
Pretty cool, although button border looks a bit awkward, its too big i think

**Comment by Dispersia** [comment]
Ya, I was going to shrink the border, make the text not get auto lower-cased and swap the colors from light - dark theme for the border. Those were the plans at least, just wanted some input from you guys ^^

**Comment by voshond** [comment]
will be done in new design
