### ISSUE TITLE
Your account has been logged in from another location before I even log in.

### ISSUE THREAD

**Issue by nemaster** [SightstoneOfficial/LegendaryClient#308]
I can log into the regular client but when i click log in on LC I get the immediate message that says "Kicked from server this account has been logged in from another location."

things ive tryed: 1.) use regular lol client [works]
                          2.) restart LC [nope]
                          3.)reinstall LC [nope]
                          4.) try another account [nope]

**Comment by Dispersia** [comment]
http://i.imgur.com/pa0QW0v.png this doesn't even make sense, the if statement returned false and went into the body anyway. Anyway, just posting I'm looking into this now.

**Comment by nemaster** [comment]
Yea, I looked all over for someone with the same issue but i got nothing. So weird haha.

**Comment by Dispersia** [comment]
This is actually really weird behavior. For some reason it's returning that we aren't logging in at all, hmm.

**Comment by Dispersia** [comment]
Just curious, have you ever logged into garena?

**Comment by nemaster** [comment]
No I havnt, im about to go to sleep for the night but ill start patching it now and test it tomorrow. I'll update you on that as soon as im able to.

**Comment by Dispersia** [comment]
Are you NA?

**Comment by Cwian** [comment]
I get the same problem.  I'm NA and haven't ever logged into garena.
