### ISSUE TITLE
Every Suggestion I could think of

### ISSUE THREAD

**Issue by DannyX5** [SightstoneOfficial/LegendaryClient#311]
Bugs and Suggestions:
- [x] Sometimes looking someones ingame from their profiles shows the names are not fitting in thus not showing full names make that thing wider.
- [ ] When writing in a message try to show you how much your typing since the text bar only shows last few words.
- [x] IF you dodge something and try to que it won't show error but the timer keep glitching.
- [ ] If you hover above a player in replay show case it sometimes get to stuck and stay there forever.
- [x] If you use LC and your friends hover above you, They will see you as unranked.
- [ ] Rune pages are confusing, please try to copy the same way as original lol client.
- [x] Instead of showing rune page 1,2,3 Please show the name for runes and masteries
- [ ] Open all the tabs by default expect the Offline tab in friendlist.
- [ ] Let us create group names and re-arrange tabs.
- [ ] Show how many people are online in the friendlist icon.
- [ ] Add a Save option which server to show the replays from in home screen.
- [ ] Make the leagues tab a little bit cleaner (Icons and stuff) (Kinda confusing)
- [ ] If had a long conversation in chat and minimizing and opening again start the scroll bar from bottom not from up.
- [x] Remove 30 next to icon, Its not really needed and distracting.
- [ ] Have a light color on the each tabs on friendlist like Online,Group names,offline. It kinda look glitched without it
  - [ ] Add a message event weather you got gifted, Error Messages, Division Demoted Promoted, Ranked Team Promoted.etc
  - [ ] If possible, Are you able to show the players inside the game that you got invited to play with? (without accepting)
- [ ] Show how much time for decay to get demoted right next to the division on the top bar.
- [ ] Options in setting that saves chat logs in client as a log file.
- [ ] Show Team Ranked in Profile and stats
- [ ] Make a option to fit more message in status by having marquee/scroll that keeps updating the status.

Garena:
- [ ] Spectating someone shows spectator server data request failed.
- [ ] Use lol.garena.com as a hostname to check ping for SG/MY Garena server in client.

P.S - The list will be updated frequently.

**Comment by nongnoobjung** [comment]
(CLARITY) Instead of showing rune page 1,2,3 Please show the name. <<< this it have already it show name rune page for me

**Comment by secretdataz** [comment]
Wow, that's a huge list.
Anyways, please use checklist for this type of issue. Thanks!

**Comment by Dispersia** [comment]
(FIX) If you use LC and your friends hover above you, They will see you as unranked.

was already fixed, just not in a release version

but thank you for the list, they'll all be added into consideration ^^

**Comment by Phorofor** [comment]
~~`(ADD): Have a countdown timer that shows the amount of time remaining until your 150 IP daily bonus is available`~~

**Comment by DannyX5** [comment]
Added one more.

**Comment by eddy5641** [comment]
Replays will be server based.
