### ISSUE TITLE
Can we make the friendlist hover prettier?

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#312]
This goes to the UI designers. Can we actually make it as good looking as the new Riot Hover stuff?
Since now our style looks pretty outdated IMO.

Just a question though. Don't wanna put any pressure on you :S

**Comment by voshond** [comment]
fix #250 and i'll do it :b

**Comment by secretdataz** [comment]
Redesigned in material-design. No longer an issue.
