### ISSUE TITLE
Problem with 1366x768 (16:9) screen size

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#317]
Menu bar is off screen.
![a](https://i.imgur.com/3CP2VZv.png)

Screen size : 1366x768
Windows 8

**Comment by voshond** [comment]
is there anyway to check the screenheight and set the windowheight? i know you can resize it for sure

**Comment by secretdataz** [comment]
I've pushed a fix. But you may have to tweak this. Please see a853908.
