### ISSUE TITLE
PVPNetConnect --> Rtmp-Sharp

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#319]
Unless you are okay with resolving tons of conflicts. I am removing pvpnetconnect and replacing it with rtmp-sharp (a wintermint component) so

**Comment by secretdataz** [comment]
turn off ci build and start porting ;)

**Comment by eddy5641** [comment]
RIP PVPNetConnect. You will be remembered

**Comment by NitroXenon** [comment]
ok cant build and debug now T_T

**Comment by eddy5641** [comment]
Try now. I just added garena, not sure it it works but I can login to na again

**Comment by horato** [comment]
I was always wondering why are you using such complicated method when astralfoxy made izi lib for that :d

**Comment by voshond** [comment]
is it still up to date? i mean isnt it discontinued?

**Comment by horato** [comment]
Sure it is, it has nothing to do with league or rito. Its a lib that utilizes RTMP protocol (is it protocol?) which won't change that easily.

**Comment by NitroXenon** [comment]
btw Snowl forked rtmp-sharp and updated once for his Poro

**Comment by nairaner** [comment]
LoLNotes dont work with RTMP-Sharp so for me for now
PVPNet 1 : 0 RTMP-Sharp

**Comment by eddy5641** [comment]
The problem with pvpnet (one of the reasons its gone) is that I never managed to get a queue on a restricted acc but if you want it to work with lolnotes we can switch to snowl's fork. I think he added support for lolnotes

**Comment by eddy5641** [comment]
K you should be able to use lolnotes

**Comment by eddy5641** [comment]
our new replacement for the pvpnet spasm:
[Exception] com.riotgames.platform.messaging.UnexpectedServiceException : null
[Exception] com.riotgames.platform.messaging.UnexpectedServiceException : null
[LOG] Items collection was most likely modified.
