### ISSUE TITLE
Friendlist Improvements

### ISSUE THREAD

**Issue by DannyX5** [SightstoneOfficial/LegendaryClient#325]
Something like this:

All tabs expect offline should be expanded by default.

Enhanced UI Something like this

http://i.imgur.com/CGMVz7s.png

Just a concept

Numbers on friend icon,notification icon would be good.

Remove numbers next to icons like 30, pretty useless tbh, because its kinda removing the touch of icons.

**Comment by eddy5641** [comment]
New ui work
