### ISSUE TITLE
Garena randomly crash.

### ISSUE THREAD

**Issue by pondtroid** [SightstoneOfficial/LegendaryClient#327]
After run/login about 2-3 min

(25/3/2558 13:12) [LOG]: LegendaryClient Started Up Successfully
(25/3/2558 13:12) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(25/3/2558 13:12) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:12) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(25/3/2558 13:12) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(25/3/2558 13:12) [LOG]: Newest DataDragon Version: 5.5.3
(25/3/2558 13:12) [LOG]: Current DataDragon Version: 5.5.3
(25/3/2558 13:12) [LOG]: DDragon Version (LOL Version) = 5.5.3
(25/3/2558 13:12) [LOG]: Newest Air Assets Version: 0.0.1.134
(25/3/2558 13:12) [LOG]: Current Air Assets Version: 0.0.1.134
(25/3/2558 13:12) [LOG]: Checking Theme...
(25/3/2558 13:12) [LOG]: Trying to detect League of Legends GameClient
(25/3/2558 13:12) [LOG]: League of Legends is located at: D:\GarenaLoLTH_20150121\GarenaLoLTH\GameData\Apps\LoLTH\
(25/3/2558 13:12) [LOG]: Latest League of Legends GameClient: 0.0.1.81
(25/3/2558 13:12) [LOG]: Checking if League of Legends is Up-To-Date
(25/3/2558 13:12) [LOG]: League of Legends is Up-To-Date
(25/3/2558 13:12) [LOG]: LegendaryClient Has Finished Patching
(25/3/2558 13:12) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(25/3/2558 13:13) [LOG]: Received token, it is: gta+PqCaVm3VSY+fhty3RrRQS8uxzYomTDfkbvGxjxby36daK44MtzRFjbzaO8upc8vXik8EBTkkJFA4WzwsKxyg2pl2RYJ+BMjiK2/5DFsKJ84OjCGmIakjBLKdHho5sZPmO5DBtkiYwa4y/puP6kq8+8CiWtnKJ93yjhY1EETZHzd1yWlvvGYinSSoixbWVqiN+TaUAjoqXQGSg9fEtnCqwl3oBkPo8NcdalIyoG5Dbh+tuydJsK5wSlxBOegOdpnrZDgb+3akUGSM08x/V8XgOeEWbbnmE41IPJ6hHKLhfd78Fu64z6c8N+ozObNvwQgHQYTzYkkpcZErkQ==
(25/3/2558 13:13) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:13) [EXCEPTION]: An invalid IP address was specified.
(25/3/2558 13:13) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(25/3/2558 13:13) [LOG]: Connected to th and logged in as 
(25/3/2558 13:13) [LOG]: Switching to the page: LegendaryClient.Windows.MainPage
(25/3/2558 13:13) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:13) [EXCEPTION]: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
(25/3/2558 13:13) [EXCEPTION]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
(25/3/2558 13:13) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:13) [EXCEPTION]: Invalid JSON primitive: .
(25/3/2558 13:13) [EXCEPTION]:    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
(25/3/2558 13:13) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:13) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(25/3/2558 13:13) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(25/3/2558 13:13) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:13) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(25/3/2558 13:13) [EXCEPTION]:    at xpnet.Encoding.scanLt(Byte[] buf, Int32 off, Int32 end, ContentToken token)
(25/3/2558 13:13) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/TH//?tab=overview
(25/3/2558 13:15) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:15) [EXCEPTION]: Object reference not set to an instance of an object.
(25/3/2558 13:15) [EXCEPTION]:    at LegendaryClient.Logic.Client.<DoHeartbeat>d__24.MoveNext()
(25/3/2558 13:15) [EXCEPTION]: A first chance exception was thrown
(25/3/2558 13:15) [EXCEPTION]: Object reference not set to an instance of an object.
(25/3/2558 13:15) [EXCEPTION]:    at LegendaryClient.Logic.Client.<DoHeartbeat>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
(25/3/2558 13:15) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(25/3/2558 13:15) [UNHANDLEDEXCEPTION]: Object reference not set to an instance of an object.
(25/3/2558 13:15) [UNHANDLEDEXCEPTION]:    at LegendaryClient.Logic.Client.<DoHeartbeat>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__5(Object state)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by secretdataz** [comment]
fixed
