### ISSUE TITLE
Every dropdown box label invisible when LegendaryClient is using the classic system style menus

### ISSUE THREAD

**Issue by Phorofor** [SightstoneOfficial/LegendaryClient#328]
Would it possible to have the Metro style dropdown menus back? / have these as an option?

Now **every** single dropdown box look terrible when it's unselected and I can't even see the labels unless I click on them. It's similar to the issue that I posted earlier, but it only affected very few things at the time. (https://github.com/eddy5641/LegendaryClient/issues/244)

When LegendaryClient has to use the system scheme (without the default Aero theme, otherwise it looks fine)...
![capture](https://cloud.githubusercontent.com/assets/10596864/6879580/e3e1e5da-d54f-11e4-958e-8c42e82b917e.PNG)

Is it possible to have these Metro style dropdown boxes back? Because it doesn't change based on whether LegendaryClient sees the computer as having visual styles off or on.

![capture3](https://cloud.githubusercontent.com/assets/10596864/6879583/1e5b9c56-d550-11e4-9663-5e77754f867e.PNG)

I think 8f7d832b790f12bb66177ccd45872a9e816fb85a is what caused this. When I happened to be using the previous commit (656909fee45bed369c8eef1fc9807cbb08baec12), the one before small UI updates, the dropdown boxes were fine.

**Comment by eddy5641** [comment]
I think that they are going to change that because the text is super hard to read. Blue on blue is a bad idea. at least it is like purple on green

**Comment by voshond** [comment]
Ah i think i forgot to change back a line for testing which didnt work on w8. The combobox background didnt change for some reason and and tried the same themecolorcode for the foreground and i maybe forgot to remove the background- will do when home

**Comment by Phorofor** [comment]
It's partially fixed, the invisible label thing is gone for the most part (however dropdown box labels are invisible for the Dark Steel and Light Steel interface themes) Also the text alignment for the Runes & Masteries selections seem to be a bit too low that the text cuts off.

![capture](https://cloud.githubusercontent.com/assets/10596864/6881105/238ff064-d5a5-11e4-85a4-e780eafc8f97.PNG)
_Only can read the text slightly_

Nonetheless, thanks for the fix for the most part. At least I can read most of the labels again.

**Comment by voshond** [comment]
"however dropdown box labels are invisible for the Dark Steel and Light Steel interface themes"
can you provide a screen of that? i did fix the boxes tho i think.

**Comment by Phorofor** [comment]
![capture](https://cloud.githubusercontent.com/assets/10596864/6883319/9f23fab6-d5fc-11e4-9a64-adc0513c62e7.PNG)
_Dropdown boxes on the Dark and Light Steel themes_

It was fixed for the other themes, but it looks like it was left out for the Dark Steel and Light Steel themes so it's just invisible for those themes.

The text alignment is all good now though on the Champion Select page.
