### ISSUE TITLE
Garena server team queue problem

### ISSUE THREAD

**Issue by koalafications** [SightstoneOfficial/LegendaryClient#329]
When i select team queue on normal 5v5 blind pick it crashes to desktop :(

**Comment by NitroXenon** [comment]
can you post your log?

**Comment by koalafications** [comment]
the debug.log? im sorry im a noob.

**Comment by NitroXenon** [comment]
in logs file

**Comment by koalafications** [comment]
Sorry for the late reply. Here you go.

(3/28/2015 10:01 PM) [LOG]: LegendaryClient Started Up Successfully
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(3/28/2015 10:01 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(3/28/2015 10:01 PM) [LOG]: DataDragon Version: 5.6.1
(3/28/2015 10:01 PM) [LOG]: Current DataDragon Version: 5.6.1
(3/28/2015 10:01 PM) [LOG]: DDragon Version (LOL Version) = 5.6.1
(3/28/2015 10:01 PM) [LOG]: Air Assets Version: 0.0.1.136
(3/28/2015 10:01 PM) [LOG]: Current Air Assets Version: 0.0.1.136
(3/28/2015 10:01 PM) [LOG]: Checking Theme...
(3/28/2015 10:01 PM) [LOG]: Trying to detect League of Legends GameClient
(3/28/2015 10:01 PM) [LOG]: League of Legends is located at: C:\Users\kris2\Favorites\Contacts\Desktop\Garena Plus\Apps\lolph\
(3/28/2015 10:01 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.84
(3/28/2015 10:01 PM) [LOG]: Checking if League of Legends is Up-To-Date
(3/28/2015 10:01 PM) [LOG]: League of Legends is not Up-To-Date. Please Update League Of Legends
(3/28/2015 10:01 PM) [LOG]: Received token, it is: HwlTp7IkZ8VqzySCCiA9ueRJqSxHMI7kzB0lvnoCfErVkyBx3iJLEa91K0nfST6OPBsiI23ZZpqtyW9J1xmDJiN+brVEviIdTM/anKClnaNuEQIhqXdCRKp+NDTC3kZ6k4/bj3pyEinBwUQ4MIaiZYnxUv3GZmc5m2yDpwcGxzYB/Asfn1dvYab5u4wyKhh+KN4aHiWqXWH2tLLop3VikHgtgtbZaVhyr+o2TCm5cs1/RHWmy3EVhSsbrXaFqMMteXLZb2A5IFLyMvFQoTHNggkhxb56BoukpXAlGPrmT2ZVR/iMF5SC+fVpoaQ8rKV5eRM49PXBgwLyt8a+oEk/5Q==
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: An invalid IP address was specified.
(3/28/2015 10:01 PM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(3/28/2015 10:01 PM) [LOG]: Connected to ph and logged in as Mr. Bubbles
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: Could not find file 'C:\Users\kris2\Downloads\Release\RunePages\Mr. Bubbles'.
(3/28/2015 10:01 PM) [EXCEPTION]:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:01 PM) [EXCEPTION]: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.
(3/28/2015 10:01 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:01 PM) [EXCEPTION]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:01 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:01 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(3/28/2015 10:01 PM) [EXCEPTION]: Invalid JSON primitive: .
(3/28/2015 10:01 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:01 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(3/28/2015 10:01 PM) [EXCEPTION]:    at System.Web.Script.Serialization.JavaScriptObjectDeserializer.DeserializePrimitiveObject()
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:02 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(3/28/2015 10:02 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:02 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:02 PM) [LOG]: http://matchhistory.na.leagueoflegends.com/en/#match-details/PH/271075219/129941905?tab=overview
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:02 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:02 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:02 PM) [EXCEPTION]:    at xpnet.Encoding.scanAtts(Int32 nameStart, Byte[] buf, Int32 off, Int32 end, ContentToken token)
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(3/28/2015 10:02 PM) [EXCEPTION]:    at xpnet.Encoding.scanEndTag(Byte[] buf, Int32 off, Int32 end, Token token)
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(3/28/2015 10:02 PM) [LOG]: Collection was modified; enumeration operation may not execute.
mscorlib
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Value cannot be null.
Parameter name: path1
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
(3/28/2015 10:02 PM) [ERROR]: Can't load settings from config file.
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Value cannot be null.
Parameter name: path1
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
(3/28/2015 10:02 PM) [ERROR]: Can't load settings from config file.
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: Value cannot be null.
Parameter name: path1
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
(3/28/2015 10:02 PM) [ERROR]: Can't load settings from config file.
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(3/28/2015 10:02 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:02 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(3/28/2015 10:02 PM) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(3/28/2015 10:03 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:03 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(3/28/2015 10:03 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(3/28/2015 10:03 PM) [EXCEPTION]: A first chance exception was thrown
(3/28/2015 10:03 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(3/28/2015 10:03 PM) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)

**Comment by koalafications** [comment]
Plus it crashes after champ select, Thought you should know.
