### ISSUE TITLE
User defined regular expression for chat filter

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#330]
It would be nice if we can control what we receive in chat with some default values set in place (eloboost blocking).
I have no computer access atm, only iPad so I can't help much, sorry.

TODO
- [ ] UI for adding/removing regex.
- [ ] Regex based filter instead of hardcoding words

Contributors may edit list above as needed.

**Comment by horato** [comment]
http://pastebin.com/rnWhXc8W
awesomely coded by me, feel free to use (2lazy2implement; i mean... not enough time to implement - im in work xd)

Works for both simple words & regex
