### ISSUE TITLE
Garena VN Crash after login 

### ISSUE THREAD

**Issue by cpanel10x** [SightstoneOfficial/LegendaryClient#340]
(4/24/2015 12:26 AM) [LOG]: LegendaryClient Started Up Successfully
(4/24/2015 12:26 AM) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(4/24/2015 12:26 AM) [EXCEPTION]: A first chance exception was thrown
(4/24/2015 12:26 AM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(4/24/2015 12:26 AM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(4/24/2015 12:26 AM) [LOG]: Newest DataDragon Version: 5.7.2
(4/24/2015 12:26 AM) [LOG]: Current DataDragon Version: 5.7.2
(4/24/2015 12:26 AM) [LOG]: DDragon Version (LOL Version) = 5.7.2
(4/24/2015 12:26 AM) [LOG]: Newest Air Assets Version: 0.0.1.140
(4/24/2015 12:26 AM) [LOG]: Current Air Assets Version: 0.0.1.140
(4/24/2015 12:26 AM) [LOG]: Checking Theme...
(4/24/2015 12:26 AM) [LOG]: Trying to detect League of Legends GameClient
(4/24/2015 12:26 AM) [LOG]: League of Legends is located at: F:\Data\LienMinhHuyenThoai\GameData\Apps\lolVN\
(4/24/2015 12:26 AM) [LOG]: Latest League of Legends GameClient: 0.0.1.85
(4/24/2015 12:26 AM) [LOG]: Checking if League of Legends is Up-To-Date
(4/24/2015 12:26 AM) [LOG]: League of Legends is Up-To-Date
(4/24/2015 12:26 AM) [LOG]: LegendaryClient Has Finished Patching
(4/24/2015 12:27 AM) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(4/24/2015 12:27 AM) [LOG]: Received token, it is: kacMAaaN5aa6CVQSZXXb/iKoFyGf2Q/pv5GT4wGQzia0lhIHlqp5oey0yKhbAYJdfGPvgT7SDyVApwjOniyGG+ajOEOYf2Fl0X/f4IjslLw2KNFPHHxesQgKOE2ofARcp+aVkBhBn3zKDYMPmISJKRXJta0lPM2Hr2Akc4e7PUGUVlaAVn3o3Qf0Gow3okZqUCauGC3+IGfAujy7sHUzNVDgneOc/9/WpdDJZlUiwJccSiSnghhyxHCunXBI8FzTnoTovxL/uLAapgl3EHx60Ku4w3yD7GWSA96ZqYx/P7LtyvYgyIBkk/zzcBt/ta0PNdNbqFNQCQ9WwgWKkcV9VQ==
(4/24/2015 12:27 AM) [LOG]: rate+|+90
(4/24/2015 12:27 AM) [LOG]: token+|+Iy3KneLmue0pY2LfNbNyC7HqnJs07JVwBOP4szR8Z03X8rIB8gQgqIMwGmkgAAZruX1mkNGbW22ANiRBByTL3A==
(4/24/2015 12:27 AM) [LOG]: reason+|+login_rate
(4/24/2015 12:27 AM) [LOG]: status+|+LOGIN
(4/24/2015 12:27 AM) [LOG]: delay+|+5000
(4/24/2015 12:27 AM) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(4/24/2015 12:27 AM) [LOG]: user+|+194713685
(4/24/2015 12:27 AM) [LOG]: gasToken+|+{
  "signature": "Swhyfe16tzawAbqH7O0o5Mn877+6ejRwPoECPHkg25UExukT0aIhewaZJb3frK/66+DEXQ6DqVeE3WgUSmpm5uufKNvAVuMw43MmxvxAfH6cEpIA8oJktT6Wh5kkoT3peA9VOn6yNH9Y3J0kZg9203J+mANJVYYxzIhPqgHJu5fdtLA6YhccrXfeGNsA10+q6BUQ8awZDzmNgLSA+v5xFMhwagrsXUVAc57XLtd/00Aa62D2viLiy1AS4K36NEP+wq6AVAMVVzPweDkDJXj+AaDd7d8ovdQbQU74Kgd0NvWXa17NNLInf3Hw5V9Axtw5PFO0fy1pV44FDhKiNC6S/Q==",
  "vouching_key_id": "ae226c904afe157360229b814d4e3749",
  "gas_account_id": "194713685",
  "summoner_name": null,
  "date_time": 1429809929171,
  "pvpnet_account_id": 194713685
}
(4/24/2015 12:27 AM) [EXCEPTION]: A first chance exception was thrown
(4/24/2015 12:27 AM) [EXCEPTION]: com.riotgames.platform.login.LoginFailedException : null
(4/24/2015 12:27 AM) [EXCEPTION]: 
(4/24/2015 12:27 AM) [EXCEPTION]: A first chance exception was thrown
(4/24/2015 12:27 AM) [EXCEPTION]: com.riotgames.platform.login.LoginFailedException : null
(4/24/2015 12:27 AM) [EXCEPTION]: 
(4/24/2015 12:27 AM) [EXCEPTION]: A first chance exception was thrown
(4/24/2015 12:27 AM) [EXCEPTION]: com.riotgames.platform.login.LoginFailedException : null
(4/24/2015 12:27 AM) [EXCEPTION]: 
(4/24/2015 12:27 AM) [EXCEPTION]: A first chance exception was thrown
(4/24/2015 12:27 AM) [EXCEPTION]: com.riotgames.platform.login.LoginFailedException : null
(4/24/2015 12:27 AM) [EXCEPTION]: 
(4/24/2015 12:27 AM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(4/24/2015 12:27 AM) [UNHANDLEDEXCEPTION]: com.riotgames.platform.login.LoginFailedException : null
(4/24/2015 12:27 AM) [UNHANDLEDEXCEPTION]:

**Comment by TonyRL** [comment]
Garena TW also crash after login
log: http://pastebin.com/Ep1brzcS
using dev build: 3.0.1.219

**Comment by pondtroid** [comment]
GarenaTH too
http://pastebin.com/M7fUeQqv

**Comment by nongnoobjung** [comment]
fixed https://github.com/eddy5641/LegendaryClient/commit/fd7bfda0716f1a3c55400c4387ef444e95e29d7f
