### ISSUE TITLE
Riots servers are currently unavailable.

### ISSUE THREAD

**Issue by bboingbboing** [SightstoneOfficial/LegendaryClient#342]
Hello, I just downloaded and installed LC, and I'm trying to connect to NA Live 5.9, but I'm getting this error. Never used LC before, very first time.

**Comment by bboingbboing** [comment]
Okay, well I fixed the issue that I've posted, but is there a bug right now where LegendaryClient crashes as soon as you get into champ select lobby?

**Comment by eddy5641** [comment]
Can you send the log?
We will try to fix the issue as soon as possible but some of us are doing exams or preparing for them (or finished)
