### ISSUE TITLE
[Garena] Keeps downloading files over and over again

### ISSUE THREAD

**Issue by Trizei** [SightstoneOfficial/LegendaryClient#343]
Hi,

First, the patch will stop downloading at a random part at any given time. Second, the game will not start even after opening Garena. It will crash and debug prompt will appear. Lastly, if I open it again, It downloads never ending things from http://l3cdn.riotgames.com/ and keeps overwriting my files. It keeps downloading the same files over and over again. Can you check this as soon as possible? It is really annoying.

Thank you for your hard work though.

**Comment by eddy5641** [comment]
can you send the log. BTW it is in a folder where lc is located

**Comment by secretdataz** [comment]
Does not happen on my GarenaTH client.

**Comment by Trizei** [comment]
Hi eddy5641,

I finally made it work. But there's still an on-going issue. It says "Access is denied" or "Unable to connect to Riot Games web server" after opening League of Legends.exe

**Comment by eddy5641** [comment]
can you send the lol logs? I think it may have to do with args. I will use a vpn later

**Comment by NitroXenon** [comment]
@Trizei Have a try on the new patcher and client.
