### ISSUE TITLE
Icaros Unhandled Exception

### ISSUE THREAD

**Issue by TonyRL** [SightstoneOfficial/LegendaryClient#345]
![12 3](https://cloud.githubusercontent.com/assets/11386903/7808455/f35bfab0-03c5-11e5-8c7d-63057096ea9a.png)

dump file:
puu.sh/i0X0j/b30ccc36fb.dmp
log:
http://pastebin.com/H1iKP6hy
build 3.0.1.228

**Comment by secretdataz** [comment]
Please try to reinstall .NET framework 4.5 again.
