### ISSUE TITLE
New replay system?

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#351]
I've just decompiled BaronReplays 2.0 and I got the source code. You can take a look and reference on it. 

So eddy would you like to update the replay system of LC? Or I'll try to do it on a new branch.

Here is the source code : https://github.com/NitroXenon/BaronReplays

**Comment by secretdataz** [comment]
That would violate their copyright.

**Comment by NitroXenon** [comment]
No I mean we can have a reference and we can know the format of lrf file.

**Comment by NitroXenon** [comment]
I think that we can improve our replay system in LC and make it better... Or even save replay into a lrf file, so that users can watch replays using LC or BaronReplays.

**Comment by eddy5641** [comment]
It will be a good base to improve our replay system. I do not think that we should save the replay into an lrf file because it will require more time and knowledge. We could also work on the replay server soonish and they would just need league of legends to watch the replay (with a website)

**Comment by NitroXenon** [comment]
Yea eddy you are the best <3

Btw for TW (or Garena) region, Garena seems blocked the overseas connection so we cannot make the replay server available to TW (or Garena region). I don't know whether is it true for SEA,TH or other Garena regions, but I've tested for TW on hurl.it and I got reqiest timeout.

**Comment by eddy5641** [comment]
I know most of the garena regions do that so we could include a recorder that will than upload the replay to the server

**Comment by eddy5641** [comment]
If any devs are not in the relay repo i will add you. Just message me

**Comment by NitroXenon** [comment]
Eddy are you now developing the replay server?

**Comment by NitroXenon** [comment]
We could host the server on PaaS (e.g. openshift) :)
