### ISSUE TITLE
Available Champions list have some problems

### ISSUE THREAD

**Issue by heruix** [SightstoneOfficial/LegendaryClient#353]
![champs](https://cloud.githubusercontent.com/assets/5779319/8146599/1f89f01a-1276-11e5-8b85-3c010362a1c0.png)

**Comment by nairaner** [comment]
what is the problem?

**Comment by heruix** [comment]
![champclient](https://cloud.githubusercontent.com/assets/5779319/8150689/e728c776-1326-11e5-9822-2c964082421f.jpg)
In lol client Available champs list is like this , In LegendaryClient the FreeToPlay champ display error,but Owned is correct

**Comment by eddy5641** [comment]
It is the beginner player thingy. The newer players get a different rotation in comparison to the higher level accounts. I think they did this so new players can try out champs they do not have but become experienced.

**Comment by heruix** [comment]
OK,Thank,you!

**Comment by nairaner** [comment]
it should be fixed for champ select, but i forgot to change in profile
