### ISSUE TITLE
I need a nice GUI for the Plugin system.

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#358]
Since I suck at GUI :S 
GUI gods help me please

**Comment by NitroXenon** [comment]
@mhn23

**Comment by voshond** [comment]
If you Provide the Basic functionality sure, and I would either vote to implement it into the settings or create a new menu item for the plugins.

**Comment by newchild** [comment]
I would prefer a new Menu.
Maybe a list with loaded Plugins and/or a "checklist", so you can disable Plugins?

**Comment by NitroXenon** [comment]
Menu :+1:

**Comment by voshond** [comment]
yeah gimme a sec

**Comment by voshond** [comment]
you have a pluginspage + menuitem now. moved code from mainpage.

not sure about some things but here are my thoughts:

in the menubar at the bottom is a Plugins Button now.
there we could implement a list where Plugins could add Listitems with their functionality, shortcuts, start when you in chat, whatever you can think of. so people have an easy access of launching an plugin appwide.

in addition to that the pluginspage is a sort of settingspage for plugins. i will do a mokup asap.

**Comment by voshond** [comment]
so mokup is somewhat there now, you can check it out in the menu.
tell me what you think, at the moment not quite sure about the layout, the round icons etc.

the green circle indicates the status of the plugin (active, disabled, whatever).
- i think every plugin should have a extra file for us so we know something about the plugin (who, what it does, name etc, just a sort of standart that we can read and use)

**Comment by newchild** [comment]
I will add this. Information about the Plugin will be stored inside the Python file itself (PluginName), will add descriptions tomorrow. I added getAllLoadedPlugins() for you. Hope you can do something with it. (I want to write a data serializer tomorrow, so Plugins get loaded after a restart.)

**Comment by voshond** [comment]
you are able to add me somewhere or send me a private message? since you are german you might give me some resources onto how to learn c#- all i know is xaml and learning by reading already existing code. adding code from scratch thats not xaml is kinda scary to me right now but tho i want to help and write more code myself

**Comment by newchild** [comment]
Do you have skype? If yes add me _snipped_

**Comment by voshond** [comment]
added, thanks

**Comment by voshond** [comment]
implemented, needs proper backend.
