### ISSUE TITLE
Python libs sucks

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#359]
I used 30mins to clone the whole LC project.
Python libs SUCK

**Comment by newchild** [comment]
We could zip it if you want to.

**Comment by NitroXenon** [comment]
Also the main language of this repo becomes Python in Github.

**Comment by NitroXenon** [comment]
I think zip it is better :)

**Comment by newchild** [comment]
Well either you can do it, or I'll do it when I am home ^^

**Comment by NitroXenon** [comment]
You can just do it. I gonna do revision on my physics final exam until midnight :(

**Comment by voshond** [comment]
yeah zip is better i guess, so i'm not sure what ppl can do but if we allow them to alter UI and behavior etc they could provide assets aswell without munching the plugins folder with crap and avoiding compatibility issues file wise

**Comment by newchild** [comment]
Ok I managed to do it, but I fucked up @mhn23 's commits, so I need to redo it.

**Comment by newchild** [comment]
Fixed it
