### ISSUE TITLE
DevWindow Improvement

### ISSUE THREAD

**Issue by NitroXenon** [SightstoneOfficial/LegendaryClient#361]
Command history in dev window :
Just like when you press the up key in cmd or terminal, you can see the previous command you have typed. So that we don't need to type the command again.

Gonna implement this feature in dev window.

**Comment by NitroXenon** [comment]
DevWindow seems to be useless now... It will not automatically start with Sightstone when I press start in VS.

**Comment by eddy5641** [comment]
i will be repairing
 devwin

**Comment by NitroXenon** [comment]
Thanks eddy

**Comment by secretdataz** [comment]
@NitroXenon Make sure you have rebuilt DevWin. Mine works fine.

**Comment by NitroXenon** [comment]
@secretdataz Thanks for reminding me. I'll try it later.

**Comment by NitroXenon** [comment]
@secretdataz It works now XD
