### ISSUE TITLE
Integerover/underflow @CustomGameLobby

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#365]
(15/06/2015 23:03) [UNHANDLEDEXCEPTION]: Value was either too large or too small for an Int32.
(15/06/2015 23:03) [UNHANDLEDEXCEPTION]:    at System.Convert.ToInt32(Double value)
   at LegendaryClient.Windows.CustomGameLobbyPage.<>c__DisplayClass4.<<Lobby_OnMessageReceived>b__2>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

**Comment by eddy5641** [comment]
Can you add more of the log? Sometimes the actual problem is earlier on and something else later on crashes it

**Comment by newchild** [comment]
@mhn23 Had the complete log

**Comment by secretdataz** [comment]
The int32 overflow on EUW should be fixed.
