### ISSUE TITLE
AGSXMPP

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#371]
Got to fix the errors

**Comment by secretdataz** [comment]
Aww, do it in a separate branch please :/

**Comment by NitroXenon** [comment]
Can't compile now ..

**Comment by eddy5641** [comment]
Fixing it now. Currently no friends and messaging not working

**Comment by eddy5641** [comment]
Joins chat rooms fine. Unable to send or receive messages

**Comment by eddy5641** [comment]
Private messages work. Chatrooms left

**Comment by eddy5641** [comment]
Anybody having messages sent delayed (check with chatroom in lolclient and LC)

**Comment by voshond** [comment]
@eddy5641 
yes delayed and when sending from lol to lc the lc chat gets not updated until the chatwindow is closed and opened again

EDIT:
when you are already looking into chat:
can you fix that newline and time update bug in friends chat? the time gets updated to the actual time when reopening the chatwindow and lc to lc chats and lc to lol chats are weirdly spaced by newlines and i couldnt figure it out

**Comment by Dispersia** [comment]
@mhn23
I had fixed that a long time ago, it must have gotten reverted somehow. If you go through the history of that page it should be there. I'll look at it this weekend

**Comment by voshond** [comment]
Yeah no it's true I did it. But someone made a control just for the chat. It was weird and you couldn't copy text as well. I want the exact same layout like the riot one, we are pretty close but I don't know how to store the timestamps and no clue about the newline bug as well, + even worse: LC To LC is different behaviour than LC to RIOT. So if you could figure that out would be great!

Von meinem iPhone gesendet

**Comment by Dispersia** [comment]
could you post an example of how it's different? I'm at work so I can't run it but if I see examples I can step through the code on git.

**Comment by voshond** [comment]
I will tomorrow morning, in bed right now. Will provide screens. Cheers and nice you start some work (:

Von meinem iPhone gesendet

**Comment by voshond** [comment]
@Dispersia hey there!
![capture](https://cloud.githubusercontent.com/assets/2280353/8494734/a1eae198-215f-11e5-90c3-bbdd9d407604.PNG)

So: as you can see: Messages have 1 line break too much, time gets refreshed.
About LoL to LC: when i send from LoL to LC you wont see the Messages until you hide the chatwindow and reopen it. i remember that the linebreak was LC to LoL only but seems to be crossplatform now.

**Comment by nairaner** [comment]
we dont store the time anywhere lol, will try to fix it today

**Comment by secretdataz** [comment]
I fixed this long time ago but it got reverted.

**Comment by voshond** [comment]
thats what i said, someone used a extra control just for it which was impractical.
i think we can just mimik riot there,
chat should be simple, the layout right now is fine, just needs to be updated to material Design and then its good to go. just store the times aswell, remove the extra newline, and update the messagebox when a message comes from riots client.

**Comment by nairaner** [comment]
how do you like something like this
 ![](http://puu.sh/iLKkp/3b5d0e95a9.jpg)

**Comment by voshond** [comment]
thats good!

i do prefer the "[Timestamp] Username: Message" for every Line tho.
can you make that an option?

otherwise awesome!

**Comment by voshond** [comment]
@nairaner 
good job! delay still there but everything worked so far and the setting too and settings is being saved aswell. nice (:

**Comment by nairaner** [comment]
I think now all problems are because we update presence too often, chat server throws "max_presence_rate"and we authenticate to password locked rooms using presence.

**Comment by secretdataz** [comment]
Is this considered done?
