### ISSUE TITLE
New design

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#373]
Material design maybe.

**Comment by voshond** [comment]
@LegendaryClient/owners 
i`d like to move the conversation about the Design here.

i`m currently drawing sketches and doing some shops of what it be like.
this is the platform of feedback and suggestions. everyone can upload pictures etc and we gonna comment on them, likes dislikes etc so i get a feeling of whats working and whats not.

no 01:
the goal here was to organize the homescreen into "cards" so a user could choose which cards of content he displays, order them as he wants, providing quick access to functions and information we could provide right of the homescreen by the "card method".
![p1](https://cloud.githubusercontent.com/assets/2280353/8261184/c1ef0452-16c8-11e5-8f79-fda38e74555b.png)
feedback wanted

**Comment by naeem76** [comment]
I really like that design mhn23!

**Comment by eddy5641** [comment]
I like the multi account idea but using it would be difficult to save all the accounts locally and have them safe

**Comment by secretdataz** [comment]
I like your card design. +1

**Comment by NitroXenon** [comment]
It's better than our current homepage :)
Awesome +1

**Comment by voshond** [comment]
https://github.com/LegendaryClient/LegendaryClient/tree/material-design

starting some work, would be nice if someone can confirm:
https://github.com/LegendaryClient/LegendaryClient/commit/2f642498f941a5e0d7095273c8d90f61f0700857#commitcomment-11813388

@LegendaryClient/owners

**Comment by voshond** [comment]
making progress in the branch, looks promising

**Comment by secretdataz** [comment]
Good work mate

**Comment by voshond** [comment]
@LegendaryClient/owners 
what about the Name, i really like Sightstone by now.

and here is the current stage, feedback wanted

PatcherPage
![patcherpage](https://cloud.githubusercontent.com/assets/2280353/8393496/ef8bc412-1d09-11e5-9730-dda3f85aa3ad.PNG)

LoginPage:
![loginpage](https://cloud.githubusercontent.com/assets/2280353/8393497/f467358e-1d09-11e5-9356-8fea5fa2f9d3.PNG)

Warnings:
![warning](https://cloud.githubusercontent.com/assets/2280353/8393498/fb9c63e2-1d09-11e5-8aed-31d3aff33de3.PNG)

Logo:
![sightstone_hd](https://cloud.githubusercontent.com/assets/2280353/8393546/19483234-1d0c-11e5-964f-67e0dd412747.png)

**Comment by newchild** [comment]
Holy. I really love the material design :O
This looks epic!

**Comment by NitroXenon** [comment]
WoW this is amazing. Like it :+1:

**Comment by newchild** [comment]
BTW if we are already @new design. I love this champselect design 
https://www.reddit.com/r/leagueoflegends/comments/3bdngv/champion_select_redesign_work_in_progress/
 http://i.imgur.com/Ockb5hl.png
Do you think we can do sth similiar?
(Maybe a little more in a material-design way, but I like the layout)

**Comment by secretdataz** [comment]
_cough_ small screens _cough_

**Comment by voshond** [comment]
Something breaking in small ones? I testing against 1440:900 as well in 1280:800 and 1920:1080

**Comment by secretdataz** [comment]
I was talking about @newchild's suggestion. It uses splash art instead of champ icon.
Things won't look good on small screens.

**Comment by Dispersia** [comment]
To be honest, dont care about anything under 1200 resolution. If it's that small, they need to upgrade. We're using latest technologies and technology is getting cheaper, don't make something look bad so it works with smaller resolutions. Also, implement that champ select, that shit is sexy, also, we should contact that guy if he wants to help design.

**Comment by secretdataz** [comment]
My standard is 1366x768, no smaller.

**Comment by voshond** [comment]
ok about the screensize, 1200x768 is a viable thing.
i try to make the UI as expandable as possible but i agree that i dont want to support 10 year old Computers. if they really want that than i can pick a size and just hardcode it and scale it like the native client does it.

about that Champselect:
i dont like it at all. its bulky and they layout is too shabby, i will look into champ select as soon as i'm finished with the Rest of the Things on my Agenda.. a complete UI Rework will takes it time.

aswell i think there is no point of showing how many MasteryPoints your put into an Tree, its usally 21/9 anyway and Labels are indicating things just fine, or the Runes you put in, instead we could make a hover that shows a screen when selecting them but i think that information isnt really necessary

but i promise i will look into an updated version of champ select.

so far here is an image of the Mainpage at the Moment
![screen](https://cloud.githubusercontent.com/assets/2280353/8404424/d4537a32-1e44-11e5-8798-e6d2c5fe3eae.png)

**Comment by voshond** [comment]
oh yeah and its themeable so far but i havent looked into the thememanager yet, right now have to manually change it in the code, (2 lines in the app.xaml)

![capture](https://cloud.githubusercontent.com/assets/2280353/8416167/213818d0-1ea4-11e5-8611-87df2e59d3af.PNG)

**Comment by voshond** [comment]
okay i admit that thememanager scares me.
right now the theme is built on 3 Lines within the App.xaml
- Choose Dark or Light theme (ResourceDictionary Source="pack://application:,,,/MaterialDesignThemes.Wpf;component/Themes/MaterialDesignTheme.Light.xaml" )
- Choose Primary Color (ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/MaterialDesignColor.Teal.xaml")
- Choose Accent Color (ResourceDictionary Source="pack://application:,,,/MaterialDesignColors;component/Themes/MaterialDesignColor.Teal.xaml")

here is a List: https://www.google.com/design/spec/style/color.html#color-color-palette

so can someone look into the Branch and update the Theme Manager?

@secretdataz or @Dispersia maybe? :b

**Comment by eddy5641** [comment]
For the ui, prepare for multi acc (like a way to select multiple acc's) because i will add that in

**Comment by voshond** [comment]
@eddy5641 
i'm ready when you are

but at the moment i can't really imagine how its exactly be implemented, are we gonna define a default user? i was thinking that we add a dropdown to the upper left corner where the current icon and username is to define the default gateway such as queing, and userinfo displayed on the mainpage

and chat should be connected at all times anyway.

but since i never used wintermint and multiuser never got worked on so far i find it hard to add region contextual stuff when i dont know whereever its actually making sense.

i kind of need a defined idea what the multiuser experience should be like, or you just do it like always, you implement all features and i put them in place. but i prefer when i'm involved in the designprocess in the first place

**Comment by voshond** [comment]
something like this is UI wise simply added right now:
![user](https://cloud.githubusercontent.com/assets/2280353/8427731/f01a7542-1f19-11e5-888b-fe256257bc92.png)

**Comment by voshond** [comment]
FriendList Improvements + RegionLabels:
![screenshot 2015-07-02 02 51 45](https://cloud.githubusercontent.com/assets/2280353/8467988/964f6d5c-205d-11e5-9a9f-36368d2cdae6.png)

**Comment by secretdataz** [comment]
Wow this looks pretty.

**Comment by eddy5641** [comment]
How i was planning multi-user acc was to have a login page (user and pass on this decrypts the league of legends accs) and they can select the user to login as or to have it automatically log into the main account (user can set this in settings)
Basic info like chat status (online, away, invis), username, region and level/rank should be displayed

Some screenshots of wintermint can be found here: http://i.imgur.com/805hwO7.png

**Comment by voshond** [comment]
okay eddy i will make add an control for the User you can use and a listbox? aswell as i add a Tab to the Settings for Users, adding and selecting the default (basicly the same, not sure how to do an edit, need the code first).

will there be Region Bridging? i'd love to see that.

**Comment by voshond** [comment]
@eddy5641 how about this?

![capture](https://cloud.githubusercontent.com/assets/2280353/8488063/2193dd62-2108-11e5-81f7-fa1a77ec3fb0.PNG)

**Comment by eddy5641** [comment]
looks great :+1:

**Comment by eddy5641** [comment]
If you rename it, can you change the icon img

**Comment by voshond** [comment]
Sure i will make a new ico!

Von meinem iPhone gesendet

**Comment by voshond** [comment]
@Dispersia still have that change for the Theme Manager?

**Comment by Dispersia** [comment]
Sort of. I was going to wait until he finished the coloring part because there isn't a lot we can do with it at the moment, but if you just want a temp solution I could push it. I kind of want to work on his project a little and get that part sorted, I would love to have a color slider.

**Comment by voshond** [comment]
@eddy5641 or @secretdataz 
need help converting some Listviews into Datagrids,
right now we use hardcoded controls like LeagueItem,xaml just for viewing simple text.

The Guy from the Material Design Toolkit just updated his Framework to support Datagrids,
https://cloud.githubusercontent.com/assets/658107/8911584/57ada726-3485-11e5-8945-29d5d15d3139.gif

i think that in some cases that would remove some stuff that can be done easier maybe.

i have an example in the pluginspage.xaml if you need an datagrid.
we just have to define the columns and the rest is added backend.

preferably systemwide

**Comment by eddy5641** [comment]
Il try but I currently am set in getting rid or datadragon (rip)

**Comment by voshond** [comment]
ScreenshotsPage: 
![capture](https://cloud.githubusercontent.com/assets/2280353/8958007/2c1499fa-35fa-11e5-8dae-194761171203.PNG)

ScreenshotsOverlay:
![screenshotsviewer](https://cloud.githubusercontent.com/assets/2280353/8958065/83df59d6-35fa-11e5-80f8-2bde1d8b3ad2.PNG)

SkinsPage:
![skins](https://cloud.githubusercontent.com/assets/2280353/8958076/8ab81d42-35fa-11e5-9b88-490a42ee4e90.PNG)

**Comment by voshond** [comment]
ChampSelect:
![cawwwpture](https://cloud.githubusercontent.com/assets/2280353/9573614/b5a5ad66-4fbe-11e5-9c3c-f719e81f2a65.PNG)

tell me if this is ok or you want something new
i have to admit that champselect is incredibly hard to layout efficient but at the same time keep some visual structure you see in other pages. aswell i am not sure about the width. we need a somewhat fixed width for the Players but then there is not enough space when make it 900px width. i want increase it but 1200 default seems to be a bit high. 1050 would be enough to display everything, feedback wanted ( @secretdataz )

detailed feedback is wanted here, since its on of the most important Pages anyway.

I need Help with the ChampTrade and LockIn Icons, they are there already but the logic didnt make sense to me @NitroXenon @secretdataz @nairaner thats due the change that i dont use img for the icons and using paths instead and just have to change the visibility

**Comment by secretdataz** [comment]
Increase the width as you wish. Problems I had were involving too much height.

**Comment by voshond** [comment]
Can you test this layout in a custom botgame with 5 on each

**Comment by secretdataz** [comment]
![image](https://cloud.githubusercontent.com/assets/2021243/9628995/b4e532e8-5199-11e5-991c-231e233d45ef.png)
5th bot on enemy team isn't visible for some reason

edit : although it is visible on coop vs ai for some reason
![image](https://cloud.githubusercontent.com/assets/2021243/9629105/5d2f5780-519a-11e5-960f-11bd0cd590fe.png)

**Comment by eddy5641** [comment]
I think the chat textbox is a little small. Otherwise it is great

**Comment by voshond** [comment]
as well as the background is not working there, which almost driven me crazy because i thought it was a bug on my side.

about chat: i can move the timers up where the dodgebutton is and open up that space for us. or i resize the Champions Box to match the height of 3 Summoner controls and let the chat begin at the 5th.

**Comment by eddy5641** [comment]
I am going to start some mobile logic

**Comment by voshond** [comment]
Will do Runes next, Masteries are pretty much done, may just some polishing. Chat edited, Patcher overhauled, Working my way thru the whole Profil and then to the Play Pages.
