### ISSUE TITLE
Queue popup permanently blocks/overlays champ select screen if first queue gets denied/dodged

### ISSUE THREAD

**Issue by Nycther** [SightstoneOfficial/LegendaryClient#377]
Very reproducible for me. Enter queue, if somebody dodges or denies the initial queue pop then when you get into the champion screen after a few seconds the queue popup appears again listing everybody as ready but it never disappears, is not closable and blocks you from making any actions.

Make the queue window closable or moveable, force close on decline or something as a workaround.

Was using the bleeding edge build, but tried various other ones, including the recommended one 3.0.1.284
Queue, ARAM, team queue. Windows 7, run as administrator, tried compatibility mode for Win7.
CPU: 2770k
Ram: 12GB
GPU: GTX980
HDD: 256GB SSD

I should have taken a screenshot of the issue, but I forgot to, and currently under a long queue timer. I'll see if I can snag one later.

**Comment by nairaner** [comment]
same as #300
