### ISSUE TITLE
It's possible to bypass login queue

### ISSUE THREAD

**Issue by ghost** [SightstoneOfficial/LegendaryClient#381]
It's actually possible to bypass the login queue if you just spam the login url ("https://lq.euw1.lol.riotgames.com/login-queue/rest/queue/authenticate") 7-8 times. You will almost everytime get a valid token which you then can use to login with.

Often you will to placed in queue if you are login in multiple times over a short period of time but with this little trick you will be able to bypass the login queue. :) I hope it get's implemented in LC.

**Comment by secretdataz** [comment]
Rito will not like this.

**Comment by ghost** [comment]
Rito don't like LC...
