### ISSUE TITLE
Client crashes because of GameScouter when spec / launching botgame (still playable)

### ISSUE THREAD

**Issue by niktamerfdp** [SightstoneOfficial/LegendaryClient#388]
Thought i would bring that to your attention.
Whenever I start a botgame and the game scouter opens, the client crashes (http://i.imgur.com/wM07SXy.png)

It's still playable, however I can't spectate botgames due to this issue.

Only happens in botgame.
I played on EUW.

The problem is definitely from gamescouter, as it happens in GameScouter.xaml.cs line 67 (if (n.GameName != null))

**Comment by secretdataz** [comment]
Pls post the log.
I can't read french btw.

**Comment by eddy5641** [comment]
before that add: if (n == null) return;

**Comment by niktamerfdp** [comment]
secretdataz and eddy, i'll play a botgame right now and I'll send you the result (or the log if it failed). Thanks

**Comment by niktamerfdp** [comment]
Works!

You also have to add it to FriendList.xaml.cs line 439 or else you will crash when trying to spectate someone in botgame (you still won't be able to spectate him but it will prevent the crash). Thanks
