### ISSUE TITLE
Screenshots Viewer

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#390]
As I play today, I got a nice penta and screenshotted it. After the game I went through folders and folders to get my screenshot file and I got this idea.

Since we have the location of LoL. We can easily locate the screenshots folder. Why don't we make screenshot viewer?

Thoughts?

**Comment by Dispersia** [comment]
I didn't even know LoL did that. Does it save every one you hit prtscn on? If so sure go ahead, once we figure out the new UI for everything (I don't know if he's touched the replay section yet) that would be a good place to have it, just call it like Recorded Data or something. But ya, that's a good idea and not like it's hard to implement ^^

**Comment by secretdataz** [comment]
It does when you press F12. Anyways this is low priority.

Paging @mhn23.

**Comment by secretdataz** [comment]
@mhn23 please >.<

**Comment by voshond** [comment]
i will look into it as soon as the multiuser stuff is happend

**Comment by voshond** [comment]
@secretdataz 
lets make it happen in the mutliuser branch
i'll add a page, a control and a listview, you make the code behind, deal?

**Comment by secretdataz** [comment]
Make another branch from multiuser

**Comment by voshond** [comment]
Here the Screenshots so far.

Viewer:
![capture](https://cloud.githubusercontent.com/assets/2280353/8943626/9245ff66-3573-11e5-8551-6c8f2fc6b71b.PNG)

Overlay (only from Visual Studio since i'm to stupid to view the Overlay):
![capture2](https://cloud.githubusercontent.com/assets/2280353/8943666/cc2a5b96-3573-11e5-8fe9-d33a15b7fc6b.PNG)

**Comment by secretdataz** [comment]
Current progress:

Screenshot browse page is now 100% working.
I'm now working on screenshot viewer.

![](http://i.imgur.com/gPpEFth.png)

**Comment by voshond** [comment]
are you able to implement a context menu for the pictures to "show this pic in explorer"? some ppl might want to share a penta they just shot and want to upload it to some site. so this might be useful

**Comment by eddy5641** [comment]
I am working on apis. we could use the Imgur api (upload images to imgur though client)

**Comment by eddy5641** [comment]
SS
        https://api.imgur.com/oauth2/authorize?client_id=aa6f5c0c0808d49&response_type=REQUESTED_RESPONSE_TYPE&state=APPLICATION_STATE
LC
        https://api.imgur.com/oauth2/authorize?client_id=d12448afbc3df6e&response_type=REQUESTED_RESPONSE_TYPE&state=APPLICATION_STATE

**Comment by secretdataz** [comment]
Can someone not on Garena implement screenshot folder logic for non-Garena servers?

**Comment by secretdataz** [comment]
Both pages (ScreenshotsPage and ScreenshotViewer) are now fully functional on Garena servers.
Only logic for Rito servers left.

Here, have a grill pictures. xD
![image](https://cloud.githubusercontent.com/assets/2021243/9134551/6e63c9fc-3d2f-11e5-93d1-f87aa9f69bee.png)
![image](https://cloud.githubusercontent.com/assets/2021243/9134598/e3b14a5e-3d2f-11e5-975d-7807035f33de.png)
