### ISSUE TITLE
Stuck logging in.

### ISSUE THREAD

**Issue by ImAFuckingPleb** [SightstoneOfficial/LegendaryClient#393]
hello.

I have downloaded the latest verison released here: https://github.com/LegendaryClient/LegendaryClient/releases

after the client finished patching, I chose EUW and tried to login but it  was stuck on " logging in " 

here’s the log:

http://pastebin.com/hCtRfCaC

**Comment by eddy5641** [comment]
https://ci.appveyor.com/project/EddyV/legendaryclient/build/3.0.1.284/artifacts
Download and try this one

**Comment by ImAFuckingPleb** [comment]
Yup! the download link you provided has fixed this issue for me.

Thanks eddy :)
