### ISSUE TITLE
Optional secure chat connections soon™

### ISSUE THREAD

**Issue by newchild** [SightstoneOfficial/LegendaryClient#395]
Currently starting to implement my testing branch

**Comment by eddy5641** [comment]
cant sync anymore

**Comment by newchild** [comment]
What do you mean?

**Comment by eddy5641** [comment]
An error occurred. Detailed message: An error was raised by libgit2. Category = Merge (Error).
Invalid description in FETCH_HEAD line 13

6fd6b026d91625d0507dc0404944d4007189f43b    not-for-merge   branch 'newchild's-testing-Branch' of https://github.com/LegendaryClient/LegendaryClient.git

VS pls

**Comment by newchild** [comment]
Well there is pretty much nothing implemented anyways :P

**Comment by secretdataz** [comment]
NSA BOYZ

**Comment by eddy5641** [comment]
K can pull and push via command line

**Comment by eddy5641** [comment]
Do you mean the text is encrypted so server can not read

**Comment by newchild** [comment]
It will be a PGP encryption. Each user will be able to generate a key, and exchange it with LoL contacts. Then you can choose the secure chat option, which will encrypt/decrypt all your messages with the given contact automatically

**Comment by newchild** [comment]
I need help with actually exchanging the public keys. Any idea of an implementation?

**Comment by eddy5641** [comment]
You could have it in chat status and they get part of it though that then get invited to a custom came (name of game)

**Comment by voshond** [comment]
since we can detect who have LC client cant we just indicate it somehow? then add a context menu "add pgp key" and put it in a popup box

**Comment by newchild** [comment]
If we can somehow add it to a userstatus, that would be perfect, like @mhn23 said. Is this still possible @eddy5641 ?

**Comment by secretdataz** [comment]
Edit : ignore this. I'm retarded.

**Comment by eddy5641** [comment]
You add it somewhere here but you have to find a way to make it for a certain user because anybody who is your friend can see it (Maybe they add their username to a certain part?)
sb.Append("<body><profileIcon>");
            sb.Append(LoginPacket.AllSummonerData.Summoner.ProfileIconId);
            sb.Append("</profileIcon><level>");
            sb.Append(level);
            sb.Append("</level>");
            if (!hidelegendaryaddition)
            {
                sb.Append("<dev>");
                sb.Append(Dev ? "true" : "false");
                sb.Append("</dev>");
            }
            sb.Append("<wins>");
            sb.Append(AmountOfWins);
            sb.Append("</wins><leaves>0</leaves><odinWins>0</odinWins><odinLeaves>0</odinLeaves>"); // TODO
            sb.Append("<queueType />");
            sb.Append("<rankedLosses>0</rankedLosses><rankedRating>0</rankedRating>"); // unused for now
            if (!IsRanked)
                sb.Append("<tier>UNRANKED</tier>");
            else
                sb.Append("<tier>" + TierName + "</tier>");
            sb.Append("<rankedSoloRestricted>");
            sb.Append(LoginPacket.RestrictedGamesRemainingForRanked != -1);
            sb.Append("</rankedSoloRestricted>");
            if (IsRanked)
                sb.Append("<rankedLeagueName>" + LeagueName + "</rankedLeagueName><rankedLeagueDivision>" + Tier +
                          "</rankedLeagueDivision><rankedLeagueTier>" + TierName +
                          "</rankedLeagueTier><rankedLeagueQueue>RANKED_SOLO_5x5</rankedLeagueQueue><rankedWins>" +
                          AmountOfWins + "</rankedWins>");
            else
                sb.Append("<rankedLeagueName /><rankedLeagueDivision /><rankedLeagueTier /><rankedLeagueQueue />");
            sb.Append("<gameStatus>");
            sb.Append(GameStatus);
            sb.Append("</gameStatus>");
            switch (GameStatus)
            {
                case "inQueue":
                    sb.Append("<timeStamp>" + timeStampSince + "</timeStamp>");
                    break;
                case "inGame":
                    sb.Append("<gameQueueType>NONE</gameQueueType><isObservable>ALL</isObservable><skinname>");
                    sb.Append(ChampId != -1 ? champions.GetChampion(ChampId).displayName : "Unknown");
                    sb.Append("</skinname>");
                    break;
                case "championSelect":
                    sb.Append(
                        "<gameQueueType>NONE</gameQueueType><isObservable>ALL</isObservable><skinname>");
                    sb.Append(ChampId != -1 ? champions.GetChampion(ChampId).displayName : "Unknown");
                    sb.Append("</skinname>");
                    break;
            }
            if (CurrentStatus == "Online")
                sb.Append("<statusMsg />");
            else
                sb.Append("<statusMsg>" + CurrentStatus + "</statusMsg>");
            sb.Append("</body>");
