### ISSUE TITLE
Wont log in

### ISSUE THREAD

**Issue by ar1a** [SightstoneOfficial/LegendaryClient#401]
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(7/14/2015 2:14 PM) [EXCEPTION]:    at LegendaryClient.Logic.Riot.Platform.ClientSystemStatesNotification.ReadExternal(IDataInput input)
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]:    at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]:    at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
(7/14/2015 2:14 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketReader.ReadLoop() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\rtmp-sharp\Net\RtmpPacketReader.cs:line 104
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketWriter.WriteLoop() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\rtmp-sharp\Net\RtmpPacketWriter.cs:line 77

**Comment by secretdataz** [comment]
We need the FULL log :-(

**Comment by ar1a** [comment]
(7/14/2015 2:12 PM) [LOG]: LegendaryClient Started Up Successfully
(7/14/2015 2:12 PM) [LOG]: Switching to the page: LegendaryClient.Windows.PatcherPage
(7/14/2015 2:12 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:12 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(7/14/2015 2:12 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(7/14/2015 2:12 PM) [LOG]: Newest DataDragon Version: 5.13.1
(7/14/2015 2:12 PM) [LOG]: Current DataDragon Version: 5.13.1
(7/14/2015 2:12 PM) [LOG]: DDragon Version (LOL Version) = 5.13.1
(7/14/2015 2:12 PM) [LOG]: Newest Air Assets Version: 0.0.1.151
(7/14/2015 2:12 PM) [LOG]: Current Air Assets Version: 0.0.1.151
(7/14/2015 2:12 PM) [LOG]: Checking Theme...
(7/14/2015 2:12 PM) [LOG]: Trying to detect League of Legends GameClient
(7/14/2015 2:12 PM) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(7/14/2015 2:12 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.95
(7/14/2015 2:12 PM) [LOG]: Checking if League of Legends is Up-To-Date
(7/14/2015 2:12 PM) [LOG]: League of Legends is Up-To-Date
(7/14/2015 2:12 PM) [LOG]: LegendaryClient Has Finished Patching
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Index was outside the bounds of the array.
(7/14/2015 2:14 PM) [EXCEPTION]:    at LegendaryClient.Windows.LoginPage..ctor()
(7/14/2015 2:14 PM) [LOG]: Switching to the page: LegendaryClient.Windows.LoginPage
(7/14/2015 2:14 PM) [LOG]: rate+|+75
(7/14/2015 2:14 PM) [LOG]: token+|+HgsXjjtg-AlTWqEZzt4Sv8gRWhgAhr7FY1CxJUG673HdZHHBZZ7TWpyJh8udxVFsU6pd-59zGrN5QF3KoDoptA==
(7/14/2015 2:14 PM) [LOG]: reason+|+login_rate
(7/14/2015 2:14 PM) [LOG]: status+|+LOGIN
(7/14/2015 2:14 PM) [LOG]: delay+|+10000
(7/14/2015 2:14 PM) [LOG]: inGameCredentials+|+{
  "inGame": false,
  "summonerId": null,
  "serverIp": null,
  "serverPort": null,
  "encryptionKey": null,
  "handshakeToken": null
}
(7/14/2015 2:14 PM) [LOG]: user+|+niggazdontgettoseemyusernameongithub
(7/14/2015 2:14 PM) [LOG]: idToken+|+eyJhbGciOiJSUzI1NiJ9.eyJsb2wiOlt7InVpZCI6NDYwNTI2NDMsImN1aWQiOjIwMDEyNTA5MCwidW5hbWUiOiJhYWhkaW1hdyIsImNwaWQiOiJPQzEiLCJwaWQiOiJOQTEifV0sImV4cCI6MTQzNjk0MDg1Miwic3ViIjoidXJuOnJpb3Q6cGlkOnYxOk5EWXdOVEkyTkRNNlRrRXgiLCJ0YWciOltdLCJhdWQiOiJsb2wiLCJpc3MiOiJodHRwczpcL1wvZ2FzLnJpb3RnYW1lcy5jb20iLCJpYXQiOjE0MzY4NTQ0NTIsImFtciI6ImNsaWVudF9iYXNpYyJ9.kcHtNcPszxgGuyMnm1DCfgIzuQTcg8gV3pPC-Z4t4Ytrfev9ncL4WrdvcMrIC5zEuN6zh7J35VAG8JIUWiLY-aZm3exbteoi_IlbMJPvm6y8-YQ-GTIxMikMdUWOxYPhUCWkfFrg5rJuYE8A7IWUkbi9UiY77wquUAjrhCeilZUUyz8BIyFIMMNbAjpH3VrUFVwJlpKfHnqDuQOWE5TyOH2AhIp2xtznSNM4SA8u_iSgXmmo1GBkRdDmUFKOmGmCQLJG5oomSYUQ_jOx0s1eBCPpG4nopjruCnUZAIL-mc4tKDfwSa8IhLIqS4qmK7NOFFsMZeGai1wWaeADEhttdg
(7/14/2015 2:14 PM) [LOG]: gasToken+|+{
  "vouching_key_id": "ae226c904afe157360229b814d4e3749",
  "gas_account_id": "200125090",
  "signature": "erKZEkxO4QIQaA5LIA/iCJOszg5IDvEo1biUuRJURf+SERtdt2gLvCeHvC1VFgBrQmXmu1e4nh/CxhQB6rJ0sM2vD5jG/wbY/v4pMCiYzw4ICQ2fxTbuy6t/Ala5jWUzkdPw9ro8dPPFjYLsdXQoSDpTCC9xR6kSTiQlDCS+yHdmdlCddvlVoccdGDLD2pNssHXunhPu6a/8yXCeAcNcLFk5ZxeOsq23DPPdnfirelebbZFPPR9hsUZo8EHH+JjCx/eUev5Lz8TyuSudelHc87hmLbO/gfCIaPsfkuxWa7iW6RexiOAqU0CljtbyTo3yzEMswv0ex0OFM6CmwP5j3A==",
  "summoner_name": null,
  "date_time": 1436854452832,
  "pvpnet_account_id": 200125090
}
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Object reference not set to an instance of an object.
(7/14/2015 2:14 PM) [EXCEPTION]:    at LegendaryClient.Logic.Riot.Platform.ClientSystemStatesNotification.ReadExternal(IDataInput input)
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]:    at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]:    at System.Threading.WaitHandle.WaitOneNative(SafeHandle waitableSafeHandle, UInt32 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
(7/14/2015 2:14 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketReader.ReadLoop() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\rtmp-sharp\Net\RtmpPacketReader.cs:line 104
(7/14/2015 2:14 PM) [EXCEPTION]: A first chance exception was thrown
(7/14/2015 2:14 PM) [EXCEPTION]: Thread was being aborted.
(7/14/2015 2:14 PM) [EXCEPTION]:    at RtmpSharp.Net.RtmpPacketWriter.WriteLoop() in c:\Users\Krzysztof\Documents\GitHub\LegendaryClient\rtmp-sharp\Net\RtmpPacketWriter.cs:line 77

**Comment by ar1a** [comment]
I fixed it, i used github release.
switched out to appveyor and it worked
