### ISSUE TITLE
Remove ddragon

### ISSUE THREAD

**Issue by nairaner** [SightstoneOfficial/LegendaryClient#407]

**Comment by nairaner** [comment]
@Dispersia do you still have the code you was writing for swf extraction?

**Comment by eddy5641** [comment]
I think lc has one already

**Comment by nairaner** [comment]
we dont have one for image extraction, but i remember dispersia was working on it

**Comment by horato** [comment]
LC has one actually... Dispe was quite mad when he found out after he finished his extractor LOL

https://github.com/LegendaryClient/LegendaryClient/tree/master/LegendaryClient/Logic/SWF

**Comment by nairaner** [comment]
Oh ok, but i think there is only extraction to abc and we still have to get images from that

**Comment by eddy5641** [comment]
Some data is in the sqlite file. I just checked. Anyone know the files with the images for masteries and stuff?

**Comment by nairaner** [comment]
from air release manifest

```
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_backgrounds.swf,BIN_0x00000002,21884922,1213244,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_buddyIcons.swf,BIN_0x00000002,23098166,19867760,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_items.swf,BIN_0x00000002,42965926,3089693,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_masteryIcons.swf,BIN_0x00000002,46055619,1814821,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_misc.swf,BIN_0x00000002,47870440,4092100,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_playerProfile.swf,BIN_0x00000002,51962540,4009443,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_runebook.swf,BIN_0x00000002,55971983,1559219,0
/projects/lol_air_client/releases/0.0.1.152/files/assets/imagePacks/ImagePack_spells.swf,BIN_0x00000002,57531202,2431638,0
```

i will try to work on it, but i wont be home until monday

**Comment by eddy5641** [comment]
Ok. Just edit in the no ddragon Il try to finish the multi lang stuff premon but idk

**Comment by nairaner** [comment]
ok, so i finished jpegs now just have to decompress lossless bitmaps

**Comment by eddy5641** [comment]
ok il remove the patcher from sightstone

**Comment by nairaner** [comment]
Now we just wait for new patcher and it should work. If there are some other types of data we need from SWF just tell me

**Comment by nairaner** [comment]
We are still missing http://puu.sh/k6MJL/462727301d.json
The closest thing i found is 
http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/0.0.1.159/projects/lol_air_client/releases/0.0.1.159/files/assets/locale/Game/resources-en_US.swf
But it still have like nothing in compare to JSON, although i dont know which part of it we use

**Comment by Dispersia** [comment]
We don't use those. At one point we filled the champion data in with the
Json, but unless someone started using it for something its no longer
needed at all.
