### ISSUE TITLE
Read before version 4 release

### ISSUE THREAD

**Issue by eddy5641** [SightstoneOfficial/LegendaryClient#411]
Feel free to add things or mark things as finished in here.
Everything here **must** be met before version 4 (Sightstone) is released (unless noted): 
# In-Game to Out of Game
## Screenshots
- [x]  Screenshot viewer
## Replays
- [x] Are not important for this update
- [x] Are for the next release
- [x] Fix up the buggy stuff with this feature
# UI
- [ ] Runes confuse some people but maybe next update
- [ ] Finish this
- [ ] Make sure everything is readable
- [ ] Add in color sliders

Thank you mhn23 for your awesome work with the new ui. It looks **_awesome**_ so far
# Bugs
- [ ] Allow linking of github to Sightstone for auto bug reporting
- [ ] Finish a bug reporter that is not linked to Sightstone
- [ ] Check if the bug has been patched, if yes don't report
- [ ] Allow the user to send the report if they want to
- [ ] Show a msgbox telling them that Sightstone crashed and ask them if they want to restart the program
- [ ] Fix the bug very fast
- [x] If all else fails...

![feature](https://cloud.githubusercontent.com/assets/6468338/8892037/437a1542-32fe-11e5-893b-f3b1213bc035.jpg)
# Notifications
- [ ] Create a tray icon to send important messages
- [ ] Fix up the kick thing because multi-user may confuse Sightstone when kicked
# Chat
- [ ] Fix the delayed chat sending
- [ ] Fix any bugs that may be in agsxmpp
- [ ] Check if there is a better way to do things
- [ ] Finish secure chat (This will be good for chat rooms)
- [ ] Add if a user has read a message for Sightstone to Sightstone chat (can be disabled)
# Updates
## DataDragon
- [x] Is great but we will be saying goodbye
- [x] Replace it with direct images from riot (extract from files if needed)

Datadragon was great but had a few hours of delay after an official league of legends release. This will cause crashing in some cases and we have to say goodbye
## Patcher
- [x] Remove this from the main client
- [x] Download files that are needed to make Sightstone work
- [x] Convert files in the patcher to reduce the need to do so each time the client is opened
- [x] Update the League of Legends game client
- [ ] Update Sightstone to get less bugs
- [ ] Update Plugins with that setting
# Lag fixes
- [ ] Fix the client being laggy
- [ ] Remove the patcher from the main client
- [ ] Remove or commit out unused code
# Security
## Detection
- [ ] Check out what the official league client does for rtmp
- [ ] Add in any missing calls
## Encryption
- [ ] Find a way to **not allow** the user to have a super weak password if they use multi-user
- [ ] Make sure there is no flaws where sensitive info about accounts can be stolen
# Languages
- [ ] Make all the text that a user sees come through a resource dictionary
- [ ] Allow the user to select the language
- [ ] Have the sqlite file name in the dictionary to have stats in that language

You can see the English resource dictionary (In progress) <a href="https://github.com/LegendaryClient/LegendaryClient/blob/NoDDragon/Sightstone/Logic/Languages/English.xaml">here</a>. If you want to create another resource dictionary you have to add it in  <a href="https://github.com/LegendaryClient/LegendaryClient/blob/NoDDragon/Sightstone/MainWindow.xaml.cs#L70-L84l">here</a>
# Plugins
- [ ] Put all in the API repo
- [ ] Allow users to download direct from the API
- [x] Verify plugins before they go onto the API repo
# Readability of the code
- [ ] Clean up the code
- [ ] Get some way to keep the code similar to each other
- [ ] Add a lot more comments to the code
- [ ] Make the variable names understandable **no names like x**
- [ ] Dispose of unused variables

``` C#
//Example of some of the things above

/// <summary>
///    Checks if League of Legends needs to be updated
/// </summary>
/// <returns>
///    Returns true if League of Legends should be updated, otherwise false
/// </returns> 
public bool CheckForLeagueUpdate()
{
    using (var webClient = new WebClient())
    {
        //Do what you want here
    }
    return false;
}

//An exception is if it is sort easy to tell what it will do from it's name
```

I want this done because if we post the program, people may want to contribute or check for any suspicious activity (Because some people want to be safe)
# DevWindow
- [ ] Upgrades needed to this little application

**Comment by secretdataz** [comment]
IMO, If you want more clarity in development I suggest you to stop using "asdf" commit message.

**Comment by NitroXenon** [comment]
Can we also add a jumplist feature to control the chat status? Just like Windows Live Messenger or Skype.

**Comment by secretdataz** [comment]
@NitroXenon You should make a new issue about your suggestion.
tbh this issue is not needed as we have milestone page.

**Comment by newchild** [comment]
I will try to improve the encryptions stuff, once the client itself works stable. Also I will focus on the chat encryption in chatrooms first, then the personal conversations will follow.

**Comment by eddy5641** [comment]
I have an idea for the future (post version 4). Who uses Android and who uses iOS for their mobile device.

**Comment by secretdataz** [comment]
I have iDevices.

**Comment by voshond** [comment]
i'll have both for Webdev
