### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by SphurPhax** [SightstoneOfficial/LegendaryClient#416]
Hey Legendaryclient devs.!

I started to use your client and it's very good in my opinion^^ I used it a year before and I was very positive suprised! But now I installed it and I'm getting crashings if I'm joining a queue or creating a custom... Idk what's the problem but I really want to use this client^^ If you can help me, pls answer me :)

SphurPhax

**Comment by SphurPhax** [comment]
I hope my logs can help ya^^

http://www.filedropper.com/logs

**Comment by outpoints** [comment]
Same problem here
http://pastebin.com/4ms2hf77

**Comment by eddy5641** [comment]
Both chat problems
Can you tell me which version you are using?

**Comment by secretdataz** [comment]
This one is related to jabber. Can you try the latest development build to see if it work?

**Comment by outpoints** [comment]
http://i.imgur.com/Bg9UQ2r.png
wat

**Comment by eddy5641** [comment]
Did you use this one? https://ci.appveyor.com/project/EddyV/legendaryclient/build/3.0.1.284/artifacts

**Comment by SphurPhax** [comment]
Yep, I did... Can you link me a working verison or smth? ^^

**Comment by secretdataz** [comment]
try https://ci.appveyor.com/project/EddyV/legendaryclient/build/3.0.1.471/artifacts

**Comment by SphurPhax** [comment]
the exe or zip?

**Comment by nairaner** [comment]
zip

**Comment by SphurPhax** [comment]
kk testing now, thx :)

**Comment by SphurPhax** [comment]
After I logged  in, this message came : Do not play ANY games, I think they will not work ~eddy

or smth... Can I play games now or isnt it working? thx for the supp btw:)

**Comment by SphurPhax** [comment]
http://gyazo.com/921088069422829f8697a214f41b1544

**Comment by nairaner** [comment]
it should work

**Comment by SphurPhax** [comment]
Well, everytime I'm going into a game and it starts, lc is crashing... any ideas why?

**Comment by nairaner** [comment]
can you give the log?

**Comment by SphurPhax** [comment]
http://www.filedropper.com/logs_3

here they are

**Comment by SphurPhax** [comment]
do you know whats the problem?

**Comment by nairaner** [comment]
ya its gamescouter, i think its fixed in newest experimental version but cant compile to check it right now

**Comment by SphurPhax** [comment]
kk nvm, It just crashed in a coop, in normal all is working fine, thanks for oyur help!
