### ISSUE TITLE
"Riots servers are currently unavailable" on Garena VN server.

### ISSUE THREAD

**Issue by lightduy94** [SightstoneOfficial/LegendaryClient#420]
Our client still 5.15 so i typed 5.15.15_08_04_20_28 in the box in Legendary Client and login. But it say   "Riots servers are currently unavailable". Could you take a look at that?

**Comment by nairaner** [comment]
can you upload lol.properties file from lol client location? Its somewhere like or similar

```
Garena\GarenaLoL\GameData\Apps\LoLVN\Air 
```

**Comment by lightduy94** [comment]
This is my lol.properties:

host=prodvn1.lol.garenanow.com
xmpp_server_url=chatvn1.lol.garenanow.com
xmpp_accept_self_signed_cert=true
startChat=true
storeEnabled=true
enableTutorialGame=true
lobbyLandingURL=http://landinglol.garena.vn/?chuanoptienmang
ladderURL=http://lienminh.garena.vn/
helpURL=http://lienminh.garena.vn/support
lq_uri=https://lqvn1.lol.garenanow.com
storyPageURL=http://lienminh.garena.vn/
loadModuleChampionDetail=true
featuredGamesURL=http://125.212.222.163:80/observer-mode/rest/featured
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0

**Comment by nairaner** [comment]
new build should be ready soon

**Comment by lightduy94** [comment]
I hope you will reply in this thread when the buildt is ready!
Thank you for your all hard work!

**Comment by nairaner** [comment]
https://ci.appveyor.com/api/buildjobs/fnjqcknu7e5ysoh3/artifacts/Sightstone.zip

**Comment by lightduy94** [comment]
What i have to do with that?

**Comment by NitroXenon** [comment]
download and unzip it

**Comment by lightduy94** [comment]
Hello. Could you upload the full lastest client for me? I'm using my friend's client buildt about 4 months ago and now it's always crash when i open it.
Btw, i don't know how to install the client @@

**Comment by NitroXenon** [comment]
@lightduy94 
https://ci.appveyor.com/api/buildjobs/fnjqcknu7e5ysoh3/artifacts/Sightstone.zip

**Comment by lightduy94** [comment]
I open Signtstone.exe and it say Database is broken. Click OK to exit Sightstone.

**Comment by eddy5641** [comment]
can someone compile a prerelease of sightstone (use release function) and include the patcher?

**Comment by lightduy94** [comment]
Someone please upload the full client Sightstone for me @@
I really thank you!
