### ISSUE TITLE
Sightstone sets invalid game location for Garena regions

### ISSUE THREAD

**Issue by secretdataz** [SightstoneOfficial/LegendaryClient#421]
In LoginPage constructor, Sightstone uses this code to set Client.Location variable which is not valid for Garena regions.

```
Client.Location = Path.Combine(lolRootPath, "RADS", "solutions", "lol_game_client_sln",
                        "releases", solutionVersion, "deploy");
```

**Comment by NitroXenon** [comment]
Garena use GLocation variable.

**Comment by secretdataz** [comment]
Why 2 separate variable? Well, I noticed this because it broke screenshot page lol.

**Comment by eddy5641** [comment]
If a user is on both reagons, it will only be able to launch one gameclient. having to separate variables should fix that
