### ISSUE TITLE
Patcher

### ISSUE THREAD

**Issue by nairaner** [SightstoneOfficial/LegendaryClient#428]
Game client patcher only download for now, i think we will have to pack it in RAF
I disabled logger for now because it caused some crashes for me.
TODO:
Change back to async download and make it actually download files
Check for local game client version 

Probably a lot more

**Comment by eddy5641** [comment]
can someone find out how garena updates (like the urls)

**Comment by secretdataz** [comment]
http://dl.garenanow.com/lol/lolsg/patcher/lol_patch_{previous_date}to{patch_date}.exe

for example:
http://dl.garenanow.com/lol/lolsg/patcher/lol_patch_150909to150917.exe
http://dl.garenanow.com/lol/lolsg/patcher/lol_patch_150825to150909.exe
http://dl.garenanow.com/lol/lolsg/patcher/lol_patch_150807to150825.exe

**Comment by nongnoobjung** [comment]
inside garena patch exe is xdelta file for patching data zip.
