### ISSUE TITLE
Garena release

### ISSUE THREAD

**Issue by sengbb123** [SightstoneOfficial/LegendaryClient#432]
is it still work in 5.18 patch? 

if not , it will update?

work in Garena user?

**Comment by secretdataz** [comment]
It does for me.

**Comment by secretdataz** [comment]
![image](https://cloud.githubusercontent.com/assets/2021243/10115733/ce25df80-643d-11e5-8aed-11b858e301f6.png)
here's the pic of it working

**Comment by sengbb123** [comment]
work in TW 5.18 ?

**Comment by sengbb123** [comment]
where can i download legendaryclient 5.18 ..?

sightstone 4.0 ?

**Comment by secretdataz** [comment]
https://ci.appveyor.com/project/EddyV/legendaryclient/build/artifacts

**Comment by sengbb123** [comment]
i tried it before i quest you

wait , i in game , i cut screenshot for you

**Comment by sengbb123** [comment]
http://upload.lsforum.net/users/public/u33742414141444d183.jpg

http://upload.lsforum.net/users/public/n54548444444444444n183.jpg

**Comment by sengbb123** [comment]
I can't use it = =

**Comment by sengbb123** [comment]
LOG

(2015/9/26 下午 12:48) [LOG]: League of Legends is located at: C:\Program Files (x86)\GarenaLoLTW\GameData\Apps\LoLTW\lol.exe
(2015/9/26 下午 12:48) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 12:48) [EXCEPTION]: no such table: champions
(2015/9/26 下午 12:48) [EXCEPTION]:    於 SQLite.SQLite3.Prepare2(IntPtr db, String query)
(2015/9/26 下午 12:48) [LOG]: Database is broken : 
no such table: champions
Sightstone
(2015/9/26 下午 12:48) [LOG]: Switching to the page: Sightstone.Windows.LoginPage

but my tw lol.exe in D hard disk .. why it said location in C

**Comment by secretdataz** [comment]
run patcher first

**Comment by sengbb123** [comment]
u mean run LoLClient first?

i tried , still broken

**Comment by secretdataz** [comment]
Sightstone.Patcher.exe

**Comment by sengbb123** [comment]
0.0

**Comment by sengbb123** [comment]
http://upload.lsforum.net/users/public/j52464414141414444b183.jpg

how to start?

**Comment by sengbb123** [comment]
http://upload.lsforum.net/users/public/d216444222g183.jpg

can't press play button

http://upload.lsforum.net/users/public/j317575b183.jpg

chose Garena then it haven't any choose in right

**Comment by secretdataz** [comment]
select your region in patcher settings first.
if garena doesn't work, try NA or EUW.
You can select Garena region later in Sightstone main client.

**Comment by sengbb123** [comment]
ok 

why i updated it and restart , it will re update?

**Comment by sengbb123** [comment]
(2015/9/26 下午 02:54) [EXCEPTION]: 找不到檔案 'E:\Sightstone\bin\Release\Assets\champions\Aatrox_Square_0.png'。
(2015/9/26 下午 02:54) [EXCEPTION]:    於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(2015/9/26 下午 02:54) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2015/9/26 下午 02:54) [UNHANDLEDEXCEPTION]: 找不到檔案 'E:\Sightstone\bin\Release\Assets\champions\Aatrox_Square_0.png'

can't find Aatrox and Fizz square_0.png

**Comment by sengbb123** [comment]
(2015/9/26 下午 03:16) [EXCEPTION]: 找不到路徑 'E:\Sightstone\bin\Release\Assets\data\en_US\item.json' 的一部分。
(2015/9/26 下午 03:16) [EXCEPTION]:    於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
(2015/9/26 下午 03:16) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2015/9/26 下午 03:16) [UNHANDLEDEXCEPTION]: 找不到路徑 'E:\Sightstone\bin\Release\Assets\data\en_US\item.json' 的一部分。
(2015/9/26 下午 03:16) [UNHANDLEDEXCEPTION]:    於 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)

**Comment by sengbb123** [comment]
seems many data download yet = =

it is my problem? but i can press play button

**Comment by sengbb123** [comment]
hey bro , can i add you skype?

**Comment by LaujsterBoi** [comment]
Can u help me pls? Mine says the same thing
[UnhandledException] System.IO.FileNotFoundException: Could not find file 'C:\Users\Laichia\Downloads\Sightstone\Sightstone\bin\Release\Assets\champions\Fizz_Square_0.png'.
and then a bunch of stuff after that just like sengbb123's.
