### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by sengbb123** [SightstoneOfficial/LegendaryClient#433]
http://upload.lsforum.net/users/public/k32758524a183.jpg

why broken .. (TW server)

But i worked in KR server

**Comment by secretdataz** [comment]
Please include your log with the issue

**Comment by sengbb123** [comment]
(2015/9/26 下午 04:05) [LOG]: LegendaryClient Started Up Successfully
(2015/9/26 下午 04:05) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:05) [EXCEPTION]:Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' Or a dependent of one. System can not find the file specified。
(2015/9/26 下午 04:05) [EXCEPTION]:    於 System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   於 System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(2015/9/26 下午 04:05) [LOG]: DataDragon Version: 5.18.1
(2015/9/26 下午 04:05) [LOG]: Current DataDragon Version: 5.18.1
(2015/9/26 下午 04:05) [LOG]: DDragon Version (LOL Version) = 5.18.1
(2015/9/26 下午 04:05) [LOG]: Air Assets Version: 0.0.0.188
(2015/9/26 下午 04:05) [LOG]: Current Air Assets Version: 0.0.0.188
(2015/9/26 下午 04:05) [LOG]: Checking Theme...
(2015/9/26 下午 04:05) [LOG]: Trying to detect League of Legends GameClient
(2015/9/26 下午 04:05) [LOG]: League of Legends is located at: D:\Riot Games\League of Legends\
(2015/9/26 下午 04:05) [LOG]: Latest League of Legends GameClient: 0.0.0.178
(2015/9/26 下午 04:05) [LOG]: Checking if League of Legends is Up-To-Date
(2015/9/26 下午 04:05) [LOG]: League of Legends is Up-To-Date
(2015/9/26 下午 04:05) [LOG]: LegendaryClient Has Finished Patching
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Outside the bounds of the array index。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 LegendaryClient.Windows.LoginPage..ctor()
(2015/9/26 下午 04:06) [LOG]: Received token, it is: bx1DTst502odBNBCbhCydVGL0lMsCJnpZj21Xx0AbIDU8rhNfF1XB6XmSvciYuuGB+EKl0eNAFPOs8LRwApHl6rVqU4vDY0wHw6gt9SACzhvrEsEnW0kZUrkqjSC3P7vbRJoJrqwChgmcIFLA66KKWsHjfVhNNgycEYSIu8vUNfN3jJNwZzt7mxZ2+Mtt+bhiau9f0Urj/M98e7RB4yPKb7CNIVgNw799/l3Pfug1gtNdFg8OLg8nmlzB/Jpt/cOsq7gjPpUqs/th6NjwIQG/BLxR427FnXS5F5NNSLGp53oY7JLLZMvD3pwEdxCR0+CQjjEifDOdpZ4DRpXrdX/Og==
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Remote host has been forced to close an existing connection。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Unable to read data from the transport connection: remote host has been forced to close an existing connection。。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Unable to read data from the transport connection: remote host has been forced to close an existing connection。。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   於 System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   於 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Unable to read data from the transport connection: remote host has been forced to close an existing connection。。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   於 System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   於 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   於 System.Net.TlsStream.CallProcessAuthentication(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Unable to read data from the transport connection: remote host has been forced to close an existing connection。。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   於 System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   於 System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   於 System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   於 System.Net.TlsStream.CallProcessAuthentication(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Closed security control codes
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Runtime.InteropServices.SafeHandle.DangerousAddRef(Boolean& success)
   於 System.Net.SafeFreeContextBufferChannelBinding.QueryContextChannelBinding_SECURITY(SafeDeleteContext phContext, ContextAttribute contextAttribute, Bindings\* buffer, SafeFreeContextBufferChannelBinding refHandle)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Can not find member。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.DefaultBinder.BindToMethod(BindingFlags bindingAttr, MethodBase[] match, Object[]& args, ParameterModifier[] modifiers, CultureInfo cultureInfo, String[] names, Object& state)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Can not find Type'PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[]' 上的建構函式。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: can not find Type'PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[]' 上的建構函式。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: Type PVPNetConnect.RiotObjects.Platform.Broadcast.BroadcastMessage[] not supported by flash serializer
(2015/9/26 下午 04:06) [EXCEPTION]:    於 PVPNetConnect.RiotObjects.RiotGamesObject.SetFields[T](T obj, TypedObject result) 於 c:\projects\legendaryclient\PVPNetConnect\RiotObjects\RiotGamesObject.cs: 行 294
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: value too big or too small for Int32。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Convert.ToInt32(Double value)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:06) [EXCEPTION]: value too big or too small for Int32。
(2015/9/26 下午 04:06) [EXCEPTION]:    於 System.Convert.ToInt32(Double value)
(2015/9/26 下午 04:06) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:07) [EXCEPTION]: value too big or too small for Int32。
(2015/9/26 下午 04:07) [EXCEPTION]:    於 System.Convert.ToInt32(Double value)
(2015/9/26 下午 04:07) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:07) [EXCEPTION]: value too big or too small for Int32。
(2015/9/26 下午 04:07) [EXCEPTION]:    於 System.Convert.ToInt32(Double value)
(2015/9/26 下午 04:07) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:07) [EXCEPTION]: value too big or too small for Int32。
(2015/9/26 下午 04:07) [EXCEPTION]:    於 System.Convert.ToInt32(Double value)
(2015/9/26 下午 04:07) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:07) [EXCEPTION]: StartIndex not less than zero。
Parameter name: startIndex
(2015/9/26 下午 04:07) [EXCEPTION]:    於 System.String.Substring(Int32 startIndex, Int32 length)
(2015/9/26 下午 04:07) [EXCEPTION]: A first chance exception was thrown
(2015/9/26 下午 04:07) [EXCEPTION]: StartIndex not less than zero。
Parameter name: startIndex
(2015/9/26 下午 04:07) [EXCEPTION]:    於 System.String.Substring(Int32 startIndex, Int32 length)
   於 PVPNetConnect.PVPNetConnection.getGas() 於 c:\projects\legendaryclient\PVPNetConnect\PVPNetConnection.cs: 行 127
   於 LegendaryClient.Windows.LoginPage.<<GotLoginPacket>b__19>d__1c.MoveNext()
--- Throw back to the previous position an exception stack trace at the end of the ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
(2015/9/26 下午 04:07) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2015/9/26 下午 04:07) [UNHANDLEDEXCEPTION]: StartIndex not less than zero。
Parameter name: startIndex
(2015/9/26 下午 04:07) [UNHANDLEDEXCEPTION]:    於 System.String.Substring(Int32 startIndex, Int32 length)
   於 PVPNetConnect.PVPNetConnection.getGas() 於 c:\projects\legendaryclient\PVPNetConnect\PVPNetConnection.cs: 行 127
   於 LegendaryClient.Windows.LoginPage.<<GotLoginPacket>b__19>d__1c.MoveNext()
--- Throw back to the previous position an exception stack trace at the end of the ---
   於 System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   於 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   於 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   於 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   於 System.Windows.Threading.DispatcherOperation.Invoke()
   於 System.Windows.Threading.Dispatcher.ProcessQueue()
   於 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   於 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   於 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   於 MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   於 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   於 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   於 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   於 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   於 System.Windows.Threading.Dispatcher.Run()
   於 System.Windows.Application.RunDispatcher(Object ignore)
   於 System.Windows.Application.RunInternal(Window window)
   於 System.Windows.Application.Run(Window window)
   於 LegendaryClient.App.Main()

**Comment by sengbb123** [comment]
I translated some word in google translation

**Comment by NitroXenon** [comment]
Change game version in Login Page.

TW now is 5.18

**Comment by sengbb123** [comment]
you mean 5.18.1 is NA version?

I download 3.0.0 release and select garena update, still broken

my opinion:
http://upload.lsforum.net/users/public/e417554221p183.jpg

**Comment by sengbb123** [comment]
"Can't find League of Legends version file. Make sure you select correct update region"

then i press 'Find LoL Client' and select garenaTW lol.exe

it said 'Saved value, please restart the client to login'

I restart , but it still "Can't find League of Legends version file. Make sure you select correct update region"

Infinite loop .....

**Comment by NitroXenon** [comment]
Try to use this latest build:
https://ci.appveyor.com/api/buildjobs/1jeqx55ng52tv3re/artifacts/Sightstone.zip

Btw I don't think you can get into the best 3 university in HK imo because you suck in English.

**Comment by sengbb123** [comment]
sorry for my poor english

can i add you skype?

**Comment by sengbb123** [comment]
http://upload.lsforum.net/users/public/o728567r183.jpg

http://upload.lsforum.net/users/public/t4202256h183.jpg

why..

**Comment by NitroXenon** [comment]
Click "Patcher Setting" in patcher to select your region :D

**Comment by sengbb123** [comment]
http://upload.lsforum.net/users/public/b99395r183.jpg
yes i chose garena , but it haven't any opinions in right
