### ISSUE TITLE
Legendaryclient/Sightstone (Database is broken...)

### ISSUE THREAD

**Issue by SphurPhax** [SightstoneOfficial/LegendaryClient#436]
Title!

The Sightstone client is always crashing after 30 secs. cuz the Database is broken. Click OK to exit sightstone.

Can any1 help me?

**Comment by SphurPhax** [comment]
http://www.filedropper.com/logs_3

Here are logs. Hope it will help.

**Comment by estaterlama** [comment]
Same problem help pls

**Comment by bannoffee** [comment]
Same problem :(

**Comment by spix18** [comment]
start Sightstone.Patcher.exe and let it download some files , when its says FINISHED in blue ; click on play :)

**Comment by SphurPhax** [comment]
tried it already, It's not downloading after1 hour waiting... Can you link me a Download please? Or do I have to use the latest version?

**Comment by nairaner** [comment]
try using this version https://ci.appveyor.com/api/buildjobs/1d17vdjkcj23gy1d/artifacts/Sightstone.zip

**Comment by SphurPhax** [comment]
Its workin but its crashin if im creating a custom, and cant go to options

**Comment by SphurPhax** [comment]
want the logs?
