### ISSUE TITLE
Future of the Project

### ISSUE THREAD

**Issue by voshond** [SightstoneOfficial/LegendaryClient#440]
Any Plans on working on the proj atm?
@LegendaryClient/owners

**Comment by nairaner** [comment]
I wanted to start working on it when I had time (which I do right now) but for last week my internet is 0.5 Mbps download at most, so I cant test the patcher.

**Comment by voshond** [comment]
I am totally up for more. I want to use the Client atm aswell but i just cant seem to use it longer than 30min without something breaking

**Comment by Dispersia** [comment]
What branch are you testing on? And I got tired of league of legends for like 5+ months, I started playing a little again so we'll see what happens

**Comment by voshond** [comment]
V4-Dev since it seems like the one we are working on atm

**Comment by voshond** [comment]
@Dispersia well right now i started playing too (: let me know if you want to start some stuff

**Comment by naeem76** [comment]
is there any way to make the first run faster? downloading and extracting of game graphics assets takes a long time like 1 or 2 hours

**Comment by nairaner** [comment]
@naeem76 Not really, we have to download all the splash art and extracting actually takes like 5 minutes. But I guess I could make extracting take place in separate thread during download.

**Comment by naeem76** [comment]
@nairaner I guess thats on my side then, Do you have any idea why it takes so long on mine? Extracting and then it downloads some splash arts I think? But it takes 1 2  hours sometimes even more

**Comment by voshond** [comment]
did some Patcher Stuff i will push soon,
pls keep this convo about the Future of the Project.

**Comment by eddy5641** [comment]
i will be coming back soon
