### ISSUE TITLE
Stuck on logging in screen + Database is broken

### ISSUE THREAD

**Issue by ecasetycea** [SightstoneOfficial/LegendaryClient#442]
I currently have downloaded both of LegendaryClient and Sightstone, but none of them seem to work
In legendary client, i press play, i put my username and password to login, but then it stays in the logging in screen forever

In sightstone, when i open it, it comes up with an error saying database broken
![image](https://cloud.githubusercontent.com/assets/15278813/10710924/483731a6-7a74-11e5-9dc1-fd673ddca4e9.png)
![image](https://cloud.githubusercontent.com/assets/15278813/10710932/78379058-7a74-11e5-8cb8-c23cf0056b5c.png)

**Comment by nairaner** [comment]
When using sightstone you have to start Sightstone.Patcher first
