### ISSUE TITLE
Is it not going to be updated anymore?

### ISSUE THREAD

**Issue by naeem76** [SightstoneOfficial/LegendaryClient#450]

**Comment by newchild** [comment]
Still in update, but most devs don't have that much time anymore afaik

**Comment by ghost** [comment]
Honestly I don't see much reason for this with the planned client update next year.

**Comment by secretdataz** [comment]
Yeah, if the new client is "released" then I see no reason to continue working on this client.

**Comment by voshond** [comment]
maybe, maybe not. its good when there are alternatives unless rito blocks thirdparty apps like us connecting. i hope we will continue to work on it but we need more backend dev's working and polishing the code to reach stable release aswell as the return of Eddy to the proj. i like the project and what i've seen from the new client didnt really convince me to stop this. i love our baby

**Comment by nairaner** [comment]
I feel like the biggest problem is that the client grew into huge bowl of spaghetti and nobody really wants to work with it. Most of us just started learning to code with this project, which didn't help with managing the code "cleanness". 
I just feel like we would need to do a complete rewrite to achieve anything worth sharing with reddit/community, because implementing or improving anything with completely undocumented code is almost impossible

**Comment by secretdataz** [comment]
Yes, and those "asdf" commit messages drive me nuts.

**Comment by eddy5641** [comment]
I hope to start in about like a week (break)

On Fri, Dec 11, 2015 at 3:15 PM, Krzysztof Machura <notifications@github.com

**Comment by voshond** [comment]
i think the commits improved over time

**Comment by naeem76** [comment]
Appreciate all you guy's efforts, but this still needs to be a thing because even with the new league client, I'm pretty sure it won't have many of the features that you plan on having in SightStone, for example, replays, plugins, multi user client etc.

Thanks!

**Comment by horato** [comment]
Its spaghetti... someone would have to modularize & rewrite that thing.

**Comment by secretdataz** [comment]
![](https://i.imgur.com/tkUfsWW.png)  
yo

**Comment by eddy5641** [comment]
well actually i was thinking about rewriting it using caliburn.micro and maybe MEF

**Comment by NitroXenon** [comment]
Maybe we need to have a coding style guide...
