### ISSUE TITLE
LoL Client Update Garena use new token for login

### ISSUE THREAD

**Issue by nongnoobjung** [SightstoneOfficial/LegendaryClient#451]
i got lol client update garena plugin already (Internal Plugin) but still can't download new client

this parameter for use login with new client update 
this some detail from lollcu SEA Plugin

//string id="path_gamepath" text="\Apps\LoLLCU\LeagueClient\LeagueClient.exe"/>
//string id="gamefile" text="LeagueClient.exe"/>
//string id="path_gameversion" text="\Apps\LoLLCU\lollcu.version"/>
//string id="prefix_gametoken" text=" --garena-plus-token="/>

i will update more detail after i can download clientupdate

**Comment by eddy5641** [comment]
Going to rewrite a lot of the client soonish

**Comment by MaxiBoether** [comment]
@nongnoobjung Hi, it seems like you know a lot about Garena tokens etc. As currently there's no real API that works together with Garena, I'd like to develop a Garena server login. Would you like to work together with me to try to find out how that stuff works?

**Comment by NitroXenon** [comment]
@Mayesters
Do you mean logging in to LoL without Garena Plus?

**Comment by MaxiBoether** [comment]
Yeah, because I want to login to Garena League without Garena+, as my app is a command line java app that should run on Linux. I can't run Garena+ on a Linux command line :(

**Comment by secretdataz** [comment]
Have u tried sniffing Garena+'s network traffic?
got any clue?

**Comment by nongnoobjung** [comment]
@Mayesters @secretdataz   i try Sniff Packet Token After Auth From Garena Server it Encryted 
easy way use window grab token then put to linux commandline XD

**Comment by MaxiBoether** [comment]
mpf, that's what I wanted to avoid, but whatever... because my app shouldn't depend on that. anyways then do you guys know a good way to circumvent the GarenaTW ip block? I want to login to the taiwan services but as I'm based in Germany it's not easy and I just can't find a working proxy

**Comment by NitroXenon** [comment]
maybe you can try VpnGate

**Comment by NitroXenon** [comment]
I think it's better to reverse engineer the Garena+
