### ISSUE TITLE
Support for Tencent/QQ/Chinese Regions

### ISSUE THREAD

**Issue by MaxiBoether** [SightstoneOfficial/LegendaryClient#452]
Hey,

would be great if support for Chinese LoL regions could be added, but unfortunatly I currently don't have any information about IPs etc.

**Comment by nongnoobjung** [comment]
@Mayesters need sniffing some data from lolnote but lolnote not support tencent :(  maybe it can login but chat not working

**Comment by MaxiBoether** [comment]
I don't really need the chat, but I don't even have the IPs :/

**Comment by NitroXenon** [comment]
What IPs?

**Comment by NitroXenon** [comment]
@nongnoobjung
I found a app which is similar to LoLNotes by  @frostycpu. It uses RtmpSharp and has a well-designed GUI. Have a look at it :D

https://github.com/frostycpu/FinalesFunkeln
