### ISSUE TITLE
Hardfixed Text

### ISSUE THREAD

**Issue by Lolr** [SightstoneOfficial/LegendaryClient#87]
So far I've only found it in custom games, but might apear else where as well it scales down all other text besides : 
http://i.imgur.com/LtdlTGx.png

This one is fixed no matter what dimensions LegendaryClient is

**Comment by Dispersia** [comment]
Ya, that's a GUI thing on the TODO list, but it's not an actual issue so I won't deal with it till later(once the functionality is in I'll do the non-major GUI fixes)

**Comment by RoachxD** [comment]
Seems to be fixed from when I modified the Theme

**Comment by Dispersia** [comment]
was not fixed

**Comment by RoachxD** [comment]
I can't seem to reproduce, give me a tip

**Comment by eddy5641** [comment]
Try shrinking the size

**Comment by secretdataz** [comment]
We did a UI overhaul. Can be closed
